/*****************************************************************************

YASK: Yet Another Stencil Kernel
Copyright (c) 2014-2019, Intel Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

* The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.

*****************************************************************************/

// Implement TTI stencil using formulation from Devito project.
// TODO: provide a more readable TTI formulation.

// YASK stencil solution(s) in this file will be integrated into the YASK compiler utility.
#include "yask_compiler_utility_api.hpp"
using namespace std;
using namespace yask;

class TTIStencil:public yc_solution_with_radius_base
{

protected:

  // Indices & dimensions.
  yc_index_node_ptr t = new_step_index("t"); // step in time dim.
  yc_index_node_ptr x = new_domain_index("x"); // spatial dim.
  yc_index_node_ptr y = new_domain_index("y"); // spatial dim.
  yc_index_node_ptr z = new_domain_index("z"); // spatial dim.

  // Grid vars.
  yc_grid_var u = yc_grid_var("u", get_solution(), { t, x, y, z });	// Time-varying 3D wavefield grid.
  yc_grid_var v = yc_grid_var("v", get_solution(), { t, x, y, z });	// Time-varying 3D wavefield grid.
  yc_grid_var m = yc_grid_var("m", get_solution(), { x, y, z });	// Square slowness of the model.
  yc_grid_var damp = yc_grid_var("damp", get_solution(), { x, y, z });	// Boundary damping.
  yc_grid_var phi = yc_grid_var("phi", get_solution(), { x, y, z });
  yc_grid_var theta = yc_grid_var("theta", get_solution(), { x, y, z });
  yc_grid_var delta = yc_grid_var("delta", get_solution(), { x, y, z });
  yc_grid_var epsilon = yc_grid_var("epsilon", get_solution(), { x, y, z });

  // Hoisted misc time-invariant data.
  yc_grid_var ti0 = yc_grid_var("ti0", get_solution(), { x, y, z });
  yc_grid_var ti1 = yc_grid_var("ti1", get_solution(), { x, y, z });
  yc_grid_var ti2 = yc_grid_var("ti2", get_solution(), { x, y, z });
  yc_grid_var ti3 = yc_grid_var("ti3", get_solution(), { x, y, z });

public:

  // For this stencil, the 'radius' is the number of FD coefficients on
  // either side of center in each spatial dimension.
TTIStencil (int radius = 2):
  yc_solution_with_radius_base ("tti", radius)
  {
  }

  // The following statements were auto-generated by the Devito symbolic finite-difference package.

  // Define equation for 'u' and 'v' at t+1 based on values at t
  // for spatial order = 4.
  virtual void define_so4 ()
  {

    yc_number_node_ptr temp161 = 2.5e-2 * (-u (t, x - 1, y, z) + u (t, x + 1, y, z));
    yc_number_node_ptr temp163 = -7.5e-2 * u (t, x, y, z) + 1.0e-1 * u (t, x, y + 1,
								 z) -
      2.5e-2 * u (t, x, y + 2,
		   z);
    yc_number_node_ptr temp192 = 1.0e-1 * u (t, x, y, z) - 7.5e-2 * u (t, x, y - 1,
								z) -
      2.5e-2 * u (t, x, y + 1,
		   z);
    yc_number_node_ptr temp183 = -2.5e-2 * u (t, x, y, z) - 7.5e-2 * u (t, x - 2, y,
								 z) +
      1.0e-1 * u (t, x - 1, y,
		   z);
    yc_number_node_ptr temp168 =
      -7.5e-2 * u (t, x, y + 1, z) + 1.0e-1 * u (t, x + 1, y + 1,
						   z) - 2.5e-2 * u (t, x + 2,
								     y + 1,
								     z);
    yc_number_node_ptr temp197 =
      3.75e-2 * (temp161 * ti1 (x, y, z) * ti2 (x, y, z) +
		  temp163 * ti2 (x, y, z) * ti3 (x, y,
						 z) - (-7.5e-2 * u (t, x, y,
								     z) +
						       1.0e-1 * u (t, x, y,
								    z + 1) -
						       2.5e-2 * u (t, x, y,
								    z +
								    2)) *
		  ti0 (x, y, z));
    yc_number_node_ptr temp171 =
      -7.5e-2 * u (t, x + 1, y, z) + 1.0e-1 * u (t, x + 1, y + 1,
						   z) - 2.5e-2 * u (t, x + 1,
								     y + 2,
								     z);
    yc_number_node_ptr temp178 = 2.5e-2 * (u (t, x, y, z) - u (t, x - 2, y, z));
    yc_number_node_ptr temp182 =
      2.5e-2 * (-u (t, x - 2, y - 1, z) + u (t, x - 2, y + 1, z));
    yc_number_node_ptr temp190 = 1.0e-1 * u (t, x, y, z) - 7.5e-2 * u (t, x - 1, y,
								z) -
      2.5e-2 * u (t, x + 1, y,
		   z);
    yc_number_node_ptr temp173 = 2.5e-2 * (u (t, x, y, z) - u (t, x, y - 2, z));
    yc_number_node_ptr temp188 =
      2.5e-2 * (-u (t, x - 1, y - 1, z) + u (t, x - 1, y + 1, z));
    yc_number_node_ptr temp154 = 2.5e-2 * (-u (t, x, y - 1, z) + u (t, x, y + 1, z));
    yc_number_node_ptr temp186 = -2.5e-2 * u (t, x, y, z) - 7.5e-2 * u (t, x, y - 2,
								 z) +
      1.0e-1 * u (t, x, y - 1,
		   z);
    yc_number_node_ptr temp158 = -7.5e-2 * u (t, x, y, z) + 1.0e-1 * u (t, x + 1, y,
								 z) -
      2.5e-2 * u (t, x + 2, y,
		   z);
    yc_number_node_ptr temp191 =
      2.5e-2 * (-u (t, x - 1, y - 1, z) + u (t, x + 1, y - 1, z));
    yc_number_node_ptr temp184 =
      2.5e-2 * (-u (t, x - 1, y - 2, z) + u (t, x + 1, y - 2, z));
    yc_number_node_ptr temp181 =
      -7.5e-2 * u (t, x - 1, y, z) + 1.0e-1 * u (t, x - 1, y + 1,
						   z) - 2.5e-2 * u (t, x - 1,
								     y + 2,
								     z);
    yc_number_node_ptr temp176 =
      -7.5e-2 * u (t, x, y - 1, z) + 1.0e-1 * u (t, x + 1, y - 1,
						   z) - 2.5e-2 * u (t, x + 2,
								     y - 1,
								     z);
    yc_number_node_ptr temp123 =
      (2.5e-2 *
       ((v (t, x, y, z) - v (t, x, y - 2, z)) * ti0 (x, y - 1, z) * ti3 (x,
									 y - 1,
									 z) +
	(-v (t, x, y - 1, z - 1) + v (t, x, y - 1, z + 1)) * ti2 (x, y - 1,
								  z)) +
       (-7.5e-2 * v (t, x, y - 1, z) + 1.0e-1 * v (t, x + 1, y - 1, z) -
	2.5e-2 * v (t, x + 2, y - 1, z)) * ti0 (x, y - 1, z) * ti1 (x, y - 1,
								     z)) *
      ti0 (x, y - 1, z) * ti3 (x, y - 1, z);
    yc_number_node_ptr temp102 =
      (2.5e-2 *
       ((-v (t, x - 1, y, z - 1) + v (t, x - 1, y, z + 1)) * ti2 (x - 1, y,
								  z) + (-v (t,
									    x -
									    1,
									    y -
									    1,
									    z) +
									v (t,
									   x -
									   1,
									   y +
									   1,
									   z)) *
	ti0 (x - 1, y, z) * ti3 (x - 1, y, z)) + (1.0e-1 * v (t, x, y,
							       z) -
						  7.5e-2 * v (t, x - 1, y,
							       z) -
						  2.5e-2 * v (t, x + 1, y,
							       z)) * ti0 (x - 1,
									  y,
									  z) *
       ti1 (x - 1, y, z)) * ti0 (x - 1, y,
				 z) * ti1 (x - 1, y, z);
    yc_number_node_ptr temp131 =
      (2.5e-2 * (-v (t, x - 1, y, z - 2) + v (t, x + 1, y, z - 2)) *
       ti0 (x, y, z - 2) * ti1 (x, y,
				z - 2) + (-2.5e-2 * v (t, x, y,
							z) - 7.5e-2 * v (t,
									  x,
									  y,
									  z -
									  2) +
					  1.0e-1 * v (t, x, y,
						       z - 1)) * ti2 (x, y,
								      z - 2) +
       (-7.5e-2 * v (t, x, y, z - 2) + 1.0e-1 * v (t, x, y + 1, z - 2) -
	2.5e-2 * v (t, x, y + 2, z - 2)) * ti0 (x, y, z - 2) * ti3 (x, y,
								     z -
								     2)) *
      ti2 (x, y, z - 2);
    yc_number_node_ptr temp87 =
      (2.5e-2 *
       ((-v (t, x - 2, y, z - 1) + v (t, x - 2, y, z + 1)) * ti2 (x - 2, y,
								  z) + (-v (t,
									    x -
									    2,
									    y -
									    1,
									    z) +
									v (t,
									   x -
									   2,
									   y +
									   1,
									   z)) *
	ti0 (x - 2, y, z) * ti3 (x - 2, y, z)) + (-2.5e-2 * v (t, x, y,
								z) -
						  7.5e-2 * v (t, x - 2, y,
							       z) +
						  1.0e-1 * v (t, x - 1, y,
							       z)) * ti0 (x - 2,
									  y,
									  z) *
       ti1 (x - 2, y, z)) * ti0 (x - 2, y,
				 z) * ti1 (x - 2, y, z);
    yc_number_node_ptr temp47 =
      2.5e-2 * (-v (t, x - 1, y, z) + v (t, x + 1, y, z)) * ti0 (x, y,
								  z) * ti1 (x,
									    y,
									    z)
      + (-7.5e-2 * v (t, x, y, z) + 1.0e-1 * v (t, x, y, z + 1) -
	 2.5e-2 * v (t, x, y, z + 2)) * ti2 (x, y, z) + (-7.5e-2 * v (t, x,
									y,
									z) +
							  1.0e-1 * v (t, x,
								       y + 1,
								       z) -
							  2.5e-2 * v (t, x,
								       y + 2,
								       z)) *
      ti0 (x, y, z) * ti3 (x, y, z);
    yc_number_node_ptr temp110 =
      (2.5e-2 *
       ((-v (t, x, y, z) + v (t, x, y + 2, z)) * ti0 (x, y + 1, z) * ti3 (x,
									  y + 1,
									  z) +
	(-v (t, x, y + 1, z - 1) + v (t, x, y + 1, z + 1)) * ti2 (x, y + 1,
								  z)) +
       (-7.5e-2 * v (t, x, y + 1, z) + 1.0e-1 * v (t, x + 1, y + 1, z) -
	2.5e-2 * v (t, x + 2, y + 1, z)) * ti0 (x, y + 1, z) * ti1 (x, y + 1,
								     z)) *
      ti0 (x, y + 1, z) * ti3 (x, y + 1, z);
    yc_number_node_ptr temp140 =
      (2.5e-2 * (-v (t, x, y, z) + v (t, x + 2, y, z)) * ti0 (x + 1, y, z) *
       ti1 (x + 1, y,
	    z) + (-7.5e-2 * v (t, x + 1, y, z) + 1.0e-1 * v (t, x + 1, y,
							       z + 1) -
		  2.5e-2 * v (t, x + 1, y,
			       z + 2)) * ti2 (x + 1, y,
					      z) +
       (-7.5e-2 * v (t, x + 1, y, z) + 1.0e-1 * v (t, x + 1, y + 1, z) -
	2.5e-2 * v (t, x + 1, y + 2, z)) * ti0 (x + 1, y, z) * ti3 (x + 1, y,
								     z)) *
      ti0 (x + 1, y,
	   z) * ti1 (x + 1, y,
		     z);
    yc_number_node_ptr temp149 =
      (2.5e-2 * (-v (t, x - 1, y - 2, z) + v (t, x + 1, y - 2, z)) *
       ti0 (x, y - 2, z) * ti1 (x, y - 2,
				z) + (-2.5e-2 * v (t, x, y,
						    z) - 7.5e-2 * v (t, x,
								      y - 2,
								      z) +
				      1.0e-1 * v (t, x, y - 1, z)) * ti0 (x,
									   y -
									   2,
									   z) *
       ti3 (x, y - 2,
	    z) + (-7.5e-2 * v (t, x, y - 2, z) + 1.0e-1 * v (t, x, y - 2,
							       z + 1) -
		  2.5e-2 * v (t, x, y - 2, z + 2)) * ti2 (x, y - 2,
							   z)) * ti0 (x,
								      y - 2,
								      z) *
      ti3 (x, y - 2, z);
    yc_number_node_ptr temp39 =
      (2.5e-2 * ((-v (t, x, y, z - 1) + v (t, x, y, z + 1)) * ti2 (x, y,
								    z) +
		  (-v (t, x,
		       y - 1,
		       z) + v (t,
			       x,
			       y + 1,
			       z))
		  * ti0 (x, y, z) * ti3 (x, y, z)) + (-7.5e-2 * v (t, x, y,
								    z) +
						      1.0e-1 * v (t,
								   x + 1,
								   y,
								   z)
						      - 2.5e-2 * v (t, x + 2,
								     y,
								     z)) *
       ti0 (x, y,
	    z) * ti1 (x, y, z)) * ti0 (x, y, z) * ti1 (x, y, z);
    yc_number_node_ptr temp132 =
      (2.5e-2 * (-v (t, x - 1, y, z - 1) + v (t, x + 1, y, z - 1)) *
       ti0 (x, y, z - 1) * ti1 (x, y,
				z - 1) + (1.0e-1 * v (t, x, y,
						       z) - 7.5e-2 * v (t, x,
									 y,
									 z -
									 1) -
					  2.5e-2 * v (t, x, y,
						       z + 1)) * ti2 (x, y,
								      z - 1) +
       (-7.5e-2 * v (t, x, y, z - 1) + 1.0e-1 * v (t, x, y + 1, z - 1) -
	2.5e-2 * v (t, x, y + 2, z - 1)) * ti0 (x, y, z - 1) * ti3 (x, y,
								     z -
								     1)) *
      ti2 (x, y, z - 1);
    yc_number_node_ptr temp6 =
      1.0 / (8.85879567828298e-1 * damp (x, y, z) + 2.0 * m (x, y, z));
    yc_number_node_ptr temp141 =
      (2.5e-2 * (v (t, x, y, z) - v (t, x - 2, y, z)) * ti0 (x - 1, y, z) *
       ti1 (x - 1, y,
	    z) + (-7.5e-2 * v (t, x - 1, y, z) + 1.0e-1 * v (t, x - 1, y,
							       z + 1) -
		  2.5e-2 * v (t, x - 1, y,
			       z + 2)) * ti2 (x - 1, y,
					      z) +
       (-7.5e-2 * v (t, x - 1, y, z) + 1.0e-1 * v (t, x - 1, y + 1, z) -
	2.5e-2 * v (t, x - 1, y + 2, z)) * ti0 (x - 1, y, z) * ti3 (x - 1, y,
								     z)) *
      ti0 (x - 1, y,
	   z) * ti1 (x - 1, y,
		     z);
    yc_number_node_ptr temp10 =
      8.85879567828298e-1 * damp (x, y, z) - 2.0 * m (x, y, z);
    yc_number_node_ptr temp215 =
      3.75e-2 * (-temp154 * ti1 (x, y, z) + temp158 * ti3 (x, y, z)) * ti3 (x,
									     y,
									     z)
      + (temp197 * ti3 (x, y,
			z) + (3.75e-2 * (temp154 * ti3 (x, y,
							 z) + temp158 * ti1 (x,
									     y,
									     z))
			      * ti2 (x, y,
				     z) - 9.375e-4 * (-u (t, x, y, z - 1) +
						       u (t, x, y,
							  z + 1)) * ti0 (x,
									 y,
									 z)) *
	 ti1 (x, y,
	      z)) * ti2 (x,
			 y,
			 z) +
      (1.25e-2 * (temp182 * ti3 (x - 2, y, z) + temp183 * ti1 (x - 2, y, z)) *
       ti2 (x - 2,
	    y,
	    z) -
       3.125e-4 * (-u (t, x - 2, y, z - 1) + u (t, x - 2, y, z + 1)) * ti0 (x -
									     2,
									     y,
									     z))
      * ti1 (x - 2,
	     y,
	     z) * ti2 (x - 2, y,
		       z) +
      5.0e-2 * ((temp191 * ti3 (x, y - 1, z) - temp192 * ti1 (x, y - 1, z)) *
		 ti1 (x, y - 1,
		      z) +
		 (2.5e-2 * (-u (t, x - 1, y, z - 1) + u (t, x + 1, y, z - 1)) *
		  ti1 (x, y,
		       z - 1) * ti2 (x,
				     y,
				     z -
				     1) -
		  (1.0e-1 * u (t, x, y, z) - 7.5e-2 * u (t, x, y, z - 1) -
		   2.5e-2 * u (t, x,
				y,
				z + 1)) * ti0 (x, y,
					       z - 1) + (-7.5e-2 * u (t, x, y,
								       z - 1) +
							 1.0e-1 * u (t, x,
								      y + 1,
								      z - 1) -
							 2.5e-2 * u (t, x,
								      y + 2,
								      z -
								      1)) *
		  ti2 (x, y,
		       z - 1) * ti3 (x, y, z - 1)) * ti0 (x, y,
							  z - 1)) +
      (1.25e-2 * temp168 * ti1 (x, y + 1, z) * ti2 (x, y + 1, z) +
       3.125e-4 * ((-u (t, x, y, z) + u (t, x, y + 2, z)) * ti2 (x, y + 1, z) *
		    ti3 (x, y + 1,
			 z) - (-u (t, x, y + 1,
				   z - 1) + u (t, x,
					       y + 1,
					       z +
					       1)) *
		    ti0 (x, y + 1, z))) * ti2 (x, y + 1, z) * ti3 (x, y + 1,
								   z) +
      (1.25e-2 *
       (temp171 * ti2 (x + 1, y, z) * ti3 (x + 1, y, z) -
	(-7.5e-2 * u (t, x + 1, y, z) + 1.0e-1 * u (t, x + 1, y, z + 1) -
	 2.5e-2 * u (t, x + 1, y, z + 2)) * ti0 (x + 1, y,
						  z)) + 3.125e-4 * (-u (t, x,
									 y,
									 z) +
								     u (t,
									x + 2,
									y,
									z)) *
       ti1 (x + 1, y, z) * ti2 (x + 1, y, z)) * ti1 (x + 1, y,
						     z) * ti2 (x + 1, y,
							       z) +
      1.25e-2 *
      ((-temp171 * ti1 (x + 1, y, z) +
	2.5e-2 * (-u (t, x, y, z) + u (t, x + 2, y, z)) * ti3 (x + 1, y,
								z)) * ti3 (x +
									   1,
									   y,
									   z)
       + (-temp173 * ti1 (x, y - 1, z) + temp176 * ti3 (x, y - 1, z)) * ti1 (x,
									     y -
									     1,
									     z)
       + (-temp182 * ti1 (x - 2, y,
			  z) + temp183 * ti3 (x - 2, y,
					      z)) * ti3 (x - 2, y,
							 z) +
       ((temp184 * ti1 (x, y - 2, z) + temp186 * ti3 (x, y - 2, z)) * ti2 (x,
									   y -
									   2,
									   z) -
	(-7.5e-2 * u (t,
		       x,
		       y - 2,
		       z) + 1.0e-1 * u (t,
					 x,
					 y - 2,
					 z + 1) - 2.5e-2 * u (t,
							       x,
							       y - 2,
							       z
							       +
							       2))
	* ti0 (x, y - 2, z)) * ti2 (x, y - 2, z) * ti3 (x, y - 2,
							z) +
       (2.5e-2 *
	(-(u (t, x, y, z) - u (t, x, y, z - 2)) * ti0 (x, y, z - 1) +
	 (-u (t, x, y - 1, z - 1) + u (t, x, y + 1, z - 1)) * ti2 (x, y,
								   z -
								   1) *
	 ti3 (x, y, z - 1)) + (-7.5e-2 * u (t, x, y, z - 1) + 1.0e-1 * u (t,
									    x +
									    1,
									    y,
									    z
									    -
									    1)
			       - 2.5e-2 * u (t, x + 2, y, z - 1)) * ti1 (x,
									  y,
									  z -
									  1) *
	ti2 (x, y, z - 1)) * ti0 (x, y, z - 1)) - (temp197 * ti0 (x, y,
								  z) +
						   3.75e-2 * (temp161 *
							       ti3 (x, y,
								    z) -
							       temp163 * ti1 (x,
									      y,
									      z))
						   * ti1 (x, y,
							  z) +
						   1.25e-2 * (temp168 *
							       ti3 (x, y + 1,
								    z) -
							       2.5e-2 *
							       (-u (t, x, y,
								    z) + u (t,
									    x,
									    y +
									    2,
									    z))
							       * ti1 (x, y + 1,
								      z)) *
						   ti1 (x, y + 1,
							z) +
						   1.25e-2 * (temp178 *
							       ti3 (x - 1, y,
								    z) -
							       temp181 *
							       ti1 (x - 1, y,
								    z)) *
						   ti3 (x - 1, y,
							z) +
						   1.25e-2 * (temp184 *
							       ti3 (x, y - 2,
								    z) -
							       temp186 * ti1 (x,
									      y
									      -
									      2,
									      z))
						   * ti1 (x, y - 2,
							  z) +
						   5.0e-2 * (-temp188 *
							      ti1 (x - 1, y,
								   z) +
							      temp190 * ti3 (x -
									     1,
									     y,
									     z))
						   * ti3 (x - 1, y,
							  z) +
						   (1.25e-2 *
						    (temp173 * ti3 (x, y - 1,
								    z) +
						     temp176 * ti1 (x, y - 1,
								    z)) *
						    ti2 (x, y - 1,
							 z) -
						    3.125e-4 *
						    (-u (t, x, y - 1, z - 1) +
						     u (t, x, y - 1,
							z + 1)) * ti0 (x,
								       y - 1,
								       z))
						   * ti2 (x, y - 1, z) * ti3 (x,
									      y
									      -
									      1,
									      z)
						   +
						   1.25e-2 *
						   ((temp178 * ti1 (x - 1, y,
								    z) +
						     temp181 * ti3 (x - 1, y,
								    z)) *
						    ti2 (x - 1, y,
							 z) -
						    (-7.5e-2 * u (t, x - 1, y,
								   z) +
						     1.0e-1 * u (t,
								  x - 1,
								  y,
								  z +
								  1) -
						     2.5e-2 * u (t, x - 1, y,
								  z +
								  2)) * ti0 (x -
									     1,
									     y,
									     z))
						   * ti1 (x - 1,
							  y,
							  z) * ti2 (x - 1, y,
								    z) +
						   (5.0e-2 *
						    (temp188 * ti3 (x - 1, y,
								    z) +
						     temp190 * ti1 (x - 1, y,
								    z)) *
						    ti2 (x - 1, y,
							 z) -
						    1.25e-3 *
						    (-u (t, x - 1, y, z - 1) +
						     u (t, x - 1, y,
							z + 1)) * ti0 (x - 1,
								       y,
								       z)) *
						   ti1 (x - 1, y,
							z) * ti2 (x - 1, y,
								  z) +
						   5.0e-2 *
						   ((temp191 * ti1 (x, y - 1,
								    z) +
						     temp192 * ti3 (x, y - 1,
								    z)) *
						    ti2 (x, y - 1,
							 z) -
						    (-7.5e-2 * u (t, x, y - 1,
								   z) +
						     1.0e-1 * u (t,
								  x,
								  y - 1,
								  z +
								  1) -
						     2.5e-2 * u (t, x, y - 1,
								  z +
								  2)) *
						    ti0 (x, y - 1,
							 z)) * ti2 (x, y - 1,
								    z) *
						   ti3 (x, y - 1,
							z) +
						   1.25e-2 * (2.5e-2 *
							       (-(-u (t, x, y,
								      z) + u (t,
									      x,
									      y,
									      z
									      +
									      2))
								* ti0 (x, y,
								       z + 1) +
								(-u
								 (t, x, y - 1,
								  z + 1) + u (t,
									      x,
									      y
									      +
									      1,
									      z
									      +
									      1))
								* ti2 (x, y,
								       z +
								       1) *
								ti3 (x, y,
								     z + 1)) +
							       (-7.5e-2 *
								u (t, x, y,
								   z + 1) +
								1.0e-1 * u (t,
									     x +
									     1,
									     y,
									     z +
									     1)
								-
								2.5e-2 * u (t,
									     x +
									     2,
									     y,
									     z +
									     1))
							       * ti1 (x, y,
								      z +
								      1) *
							       ti2 (x, y,
								    z +
								    1)) *
						   ti0 (x, y,
							z + 1) +
						   1.25e-2 * (2.5e-2 *
							       (-u (t, x - 1, y,
								    z - 2) +
								u (t, x + 1,
								   y,
								   z -
								   2)) * ti1 (x,
									      y,
									      z
									      -
									      2)
							       * ti2 (x, y,
								      z - 2) -
							       (-2.5e-2 *
								u (t, x, y,
								   z) -
								7.5e-2 * u (t,
									     x,
									     y,
									     z -
									     2)
								+
								1.0e-1 * u (t,
									     x,
									     y,
									     z -
									     1))
							       * ti0 (x, y,
								      z - 2) +
							       (-7.5e-2 *
								u (t, x, y,
								   z - 2) +
								1.0e-1 * u (t,
									     x,
									     y +
									     1,
									     z -
									     2)
								-
								2.5e-2 * u (t,
									     x,
									     y +
									     2,
									     z -
									     2))
							       * ti2 (x, y,
								      z -
								      2) *
							       ti3 (x, y,
								    z -
								    2)) *
						   ti0 (x, y, z - 2));
    yc_number_node_ptr temp77 =
      (2.5e-2 * ((v (t, x, y, z) - v (t, x, y, z - 2)) * ti2 (x, y,
							       z - 1) + (-v (t,
									     x,
									     y -
									     1,
									     z -
									     1)
									 + v (t,
									      x,
									      y
									      +
									      1,
									      z
									      -
									      1))
		  * ti0 (x, y, z - 1) * ti3 (x, y, z - 1)) + (-7.5e-2 * v (t,
									    x,
									    y,
									    z -
									    1) +
							      1.0e-1 * v (t,
									   x +
									   1, y,
									   z -
									   1) -
							      2.5e-2 * v (t,
									   x +
									   2, y,
									   z -
									   1)) *
       ti0 (x,
	    y,
	    z - 1) * ti1 (x, y, z - 1)) * ti2 (x, y, z - 1);
    yc_number_node_ptr temp61 =
      (2.5e-2 * ((-v (t, x, y, z) + v (t, x, y, z + 2)) * ti2 (x, y,
								z + 1) + (-v (t,
									      x,
									      y
									      -
									      1,
									      z
									      +
									      1)
									  +
									  v (t,
									     x,
									     y +
									     1,
									     z +
									     1))
		  * ti0 (x, y, z + 1) * ti3 (x, y, z + 1)) + (-7.5e-2 * v (t,
									    x,
									    y,
									    z +
									    1) +
							      1.0e-1 * v (t,
									   x +
									   1, y,
									   z +
									   1) -
							      2.5e-2 * v (t,
									   x +
									   2, y,
									   z +
									   1)) *
       ti0 (x,
	    y,
	    z + 1) * ti1 (x, y, z + 1)) * ti2 (x, y, z + 1);
    yc_number_node_ptr temp150 =
      (2.5e-2 * (-v (t, x - 1, y - 1, z) + v (t, x + 1, y - 1, z)) *
       ti0 (x, y - 1, z) * ti1 (x, y - 1,
				z) + (1.0e-1 * v (t, x, y,
						   z) - 7.5e-2 * v (t, x,
								     y - 1,
								     z) -
				      2.5e-2 * v (t, x, y + 1, z)) * ti0 (x,
									   y -
									   1,
									   z) *
       ti3 (x, y - 1,
	    z) + (-7.5e-2 * v (t, x, y - 1, z) + 1.0e-1 * v (t, x, y - 1,
							       z + 1) -
		  2.5e-2 * v (t, x, y - 1, z + 2)) * ti2 (x, y - 1,
							   z)) * ti0 (x,
								      y - 1,
								      z) *
      ti3 (x, y - 1, z);

    // Next time-step values.
    u (t + 1, x, y,
       z) EQUALS temp6 *(temp10 * u (t - 1, x, y,
				     z) +
			 1.5695652173913 * (temp215 * epsilon (x, y, z) +
					     (3.75e-2 *
					      (temp39 +
					       temp47 * (ti0 (x, y, z) *
							 ti3 (x, y,
							      z) + ti2 (x, y,
									z))) -
					      5.0e-2 * (temp102 + temp132 +
							 temp150) +
					      1.25e-2 * (temp110 - temp123 +
							  temp131 + temp140 -
							  temp141 + temp149 +
							  temp61 - temp77 +
							  temp87)) * delta (x,
									    y,
									    z))
			 + 4.0 * m (x, y, z) * u (t, x, y, z));
    v (t + 1, x, y,
       z) EQUALS temp6 *(temp10 * v (t - 1, x, y,
				     z) + 1.5695652173913 * temp215 * delta (x,
									      y,
									      z)
			 + 5.88586956521739e-2 * (temp39 +
						   temp47 * (ti0 (x, y, z) *
							     ti3 (x, y,
								  z) + ti2 (x,
									    y,
									    z)))
			 - 7.84782608695652e-2 * (temp102 + temp132 +
						   temp150) +
			 1.96195652173913e-2 * (temp110 - temp123 + temp131 +
						 temp140 - temp141 + temp149 +
						 temp61 - temp77 + temp87) +
			 4.0 * m (x, y, z) * v (t, x, y, z));

  }

  // Define equation for 'u' and 'v' at t+1 based on values at t
  // for spatial order = 8.
  virtual void define_so8 ()
  {

    yc_number_node_ptr temp330 =
      4.16666666666667e-3 * (u (t, x - 2, y, z) - u (t, x + 2, y, z)) +
      3.33333333333333e-2 * (-u (t, x - 1, y, z) + u (t, x + 1, y, z));
    yc_number_node_ptr temp333 =
      -4.16666666666667e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 1,
							     z) +
      7.5e-2 * u (t, x, y + 1, z) - 2.5e-2 * u (t, x, y + 2,
						  z) +
      4.16666666666667e-3 * u (t, x, y + 3, z);
    yc_number_node_ptr temp336 =
      3.33333333333333e-2 * (-u (t, x, y, z) + u (t, x, y + 2, z)) +
      4.16666666666667e-3 * (u (t, x, y - 1, z) - u (t, x, y + 3, z));
    yc_number_node_ptr temp395 =
      4.16666666666667e-3 * (u (t, x - 2, y - 2, z) - u (t, x + 2, y - 2,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 1,
				  y - 2,
				  z) + u (t,
					  x + 1,
					  y - 2,
					  z));
    yc_number_node_ptr temp365 =
      -4.16666666666667e-2 * u (t, x - 2, y, z) - 1.25e-2 * u (t, x - 2,
								 y - 1,
								 z) +
      7.5e-2 * u (t, x - 2, y + 1, z) - 2.5e-2 * u (t, x - 2, y + 2,
						      z) +
      4.16666666666667e-3 * u (t, x - 2, y + 3, z);
    yc_number_node_ptr temp375 =
      -4.16666666666667e-2 * u (t, x + 2, y, z) - 1.25e-2 * u (t, x + 2,
								 y - 1,
								 z) +
      7.5e-2 * u (t, x + 2, y + 1, z) - 2.5e-2 * u (t, x + 2, y + 2,
						      z) +
      4.16666666666667e-3 * u (t, x + 2, y + 3, z);
    yc_number_node_ptr temp394 = -2.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x - 3, y,
								  z) -
      4.16666666666667e-2 * u (t, x - 2, y, z) + 7.5e-2 * u (t, x - 1, y,
							       z) +
      4.16666666666667e-3 * u (t, x + 1, y, z);
    yc_number_node_ptr temp407 =
      4.16666666666667e-3 * (u (t, x - 1, y - 2, z) - u (t, x - 1, y + 2,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 1,
				  y - 1,
				  z) + u (t,
					  x - 1,
					  y + 1,
					  z));
    yc_number_node_ptr temp352 =
      4.16666666666667e-3 * (-u (t, x, y, z) + u (t, x, y - 4, z)) +
      3.33333333333333e-2 * (-u (t, x, y - 3, z) + u (t, x, y - 1, z));
    yc_number_node_ptr temp347 =
      -4.16666666666667e-2 * u (t, x + 1, y, z) - 1.25e-2 * u (t, x + 1,
								 y - 1,
								 z) +
      7.5e-2 * u (t, x + 1, y + 1, z) - 2.5e-2 * u (t, x + 1, y + 2,
						      z) +
      4.16666666666667e-3 * u (t, x + 1, y + 3, z);
    yc_number_node_ptr temp409 =
      4.16666666666667e-3 * (u (t, x + 1, y - 2, z) - u (t, x + 1, y + 2,
							  z)) +
      3.33333333333333e-2 * (-u (t, x + 1,
				  y - 1,
				  z) + u (t,
					  x + 1,
					  y + 1,
					  z));
    yc_number_node_ptr temp318 =
      4.16666666666667e-3 * (u (t, x, y - 2, z) - u (t, x, y + 2, z)) +
      3.33333333333333e-2 * (-u (t, x, y - 1, z) + u (t, x, y + 1, z));
    yc_number_node_ptr temp381 =
      -4.16666666666667e-2 * u (t, x, y - 1, z) - 1.25e-2 * u (t, x - 1,
								 y - 1,
								 z) +
      7.5e-2 * u (t, x + 1, y - 1, z) - 2.5e-2 * u (t, x + 2, y - 1,
						      z) +
      4.16666666666667e-3 * u (t, x + 3, y - 1, z);
    yc_number_node_ptr temp408 = 7.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x - 2, y,
								 z) -
      4.16666666666667e-2 * u (t, x - 1, y, z) - 2.5e-2 * u (t, x + 1, y,
							       z) +
      4.16666666666667e-3 * u (t, x + 2, y, z);
    yc_number_node_ptr temp390 =
      4.16666666666667e-3 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 4,
							    z) -
      4.16666666666667e-2 * u (t, x, y - 3, z) + 7.5e-2 * u (t, x, y - 2,
							       z) -
      2.5e-2 * u (t, x, y - 1, z);
    yc_number_node_ptr temp360 =
      4.16666666666667e-3 * (-u (t, x, y, z) + u (t, x - 4, y, z)) +
      3.33333333333333e-2 * (-u (t, x - 3, y, z) + u (t, x - 1, y, z));
    yc_number_node_ptr temp370 =
      -4.16666666666667e-2 * u (t, x, y + 2, z) - 1.25e-2 * u (t, x - 1,
								 y + 2,
								 z) +
      7.5e-2 * u (t, x + 1, y + 2, z) - 2.5e-2 * u (t, x + 2, y + 2,
						      z) +
      4.16666666666667e-3 * u (t, x + 3, y + 2, z);
    yc_number_node_ptr temp357 =
      -4.16666666666667e-2 * u (t, x, y - 2, z) - 1.25e-2 * u (t, x - 1,
								 y - 2,
								 z) +
      7.5e-2 * u (t, x + 1, y - 2, z) - 2.5e-2 * u (t, x + 2, y - 2,
						      z) +
      4.16666666666667e-3 * u (t, x + 3, y - 2, z);
    yc_number_node_ptr temp385 =
      -4.16666666666667e-2 * u (t, x - 1, y, z) - 1.25e-2 * u (t, x - 1,
								 y - 1,
								 z) +
      7.5e-2 * u (t, x - 1, y + 1, z) - 2.5e-2 * u (t, x - 1, y + 2,
						      z) +
      4.16666666666667e-3 * u (t, x - 1, y + 3, z);
    yc_number_node_ptr temp377 =
      3.33333333333333e-2 * (u (t, x, y, z) - u (t, x, y - 2, z)) +
      4.16666666666667e-3 * (u (t, x, y - 3, z) - u (t, x, y + 1, z));
    yc_number_node_ptr temp343 =
      3.33333333333333e-2 * (-u (t, x, y, z) + u (t, x + 2, y, z)) +
      4.16666666666667e-3 * (u (t, x - 1, y, z) - u (t, x + 3, y, z));
    yc_number_node_ptr temp388 =
      4.16666666666667e-3 * (u (t, x - 2, y - 3, z) - u (t, x + 2, y - 3,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 1,
				  y - 3,
				  z) + u (t,
					  x + 1,
					  y - 3,
					  z));
    yc_number_node_ptr temp406 =
      -1.25e-2 * u (t, x, y, z) - 4.16666666666667e-2 * u (t, x, y + 1,
							     z) +
      7.5e-2 * u (t, x, y + 2, z) - 2.5e-2 * u (t, x, y + 3,
						  z) +
      4.16666666666667e-3 * u (t, x, y + 4, z);
    yc_number_node_ptr temp404 =
      4.16666666666667e-3 * (u (t, x - 2, y + 1, z) - u (t, x + 2, y + 1,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 1,
				  y + 1,
				  z) + u (t,
					  x + 1,
					  y + 1,
					  z));
    yc_number_node_ptr temp342 =
      -4.16666666666667e-2 * u (t, x, y + 1, z) - 1.25e-2 * u (t, x - 1,
								 y + 1,
								 z) +
      7.5e-2 * u (t, x + 1, y + 1, z) - 2.5e-2 * u (t, x + 2, y + 1,
						      z) +
      4.16666666666667e-3 * u (t, x + 3, y + 1, z);
    yc_number_node_ptr temp410 =
      -1.25e-2 * u (t, x, y, z) - 4.16666666666667e-2 * u (t, x + 1, y,
							     z) +
      7.5e-2 * u (t, x + 2, y, z) - 2.5e-2 * u (t, x + 3, y,
						  z) +
      4.16666666666667e-3 * u (t, x + 4, y, z);
    yc_number_node_ptr temp367 =
      4.16666666666667e-3 * (u (t, x, y, z) - u (t, x, y + 4, z)) +
      3.33333333333333e-2 * (-u (t, x, y + 1, z) + u (t, x, y + 3, z));
    yc_number_node_ptr temp399 =
      4.16666666666667e-3 * (u (t, x - 2, y - 1, z) - u (t, x + 2, y - 1,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 1,
				  y - 1,
				  z) + u (t,
					  x + 1,
					  y - 1,
					  z));
    yc_number_node_ptr temp325 =
      -4.16666666666667e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x - 1, y,
							     z) +
      7.5e-2 * u (t, x + 1, y, z) - 2.5e-2 * u (t, x + 2, y,
						  z) +
      4.16666666666667e-3 * u (t, x + 3, y, z);
    yc_number_node_ptr temp386 =
      4.16666666666667e-3 * (u (t, x - 3, y - 2, z) - u (t, x - 3, y + 2,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 3,
				  y - 1,
				  z) + u (t,
					  x - 3,
					  y + 1,
					  z));
    yc_number_node_ptr temp396 = -2.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 3,
								  z) -
      4.16666666666667e-2 * u (t, x, y - 2, z) + 7.5e-2 * u (t, x, y - 1,
							       z) +
      4.16666666666667e-3 * u (t, x, y + 1, z);
    yc_number_node_ptr temp401 = 7.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 2,
								 z) -
      4.16666666666667e-2 * u (t, x, y - 1, z) - 2.5e-2 * u (t, x, y + 1,
							       z) +
      4.16666666666667e-3 * u (t, x, y + 2, z);
    yc_number_node_ptr temp372 =
      4.16666666666667e-3 * (u (t, x, y, z) - u (t, x + 4, y, z)) +
      3.33333333333333e-2 * (-u (t, x + 1, y, z) + u (t, x + 3, y, z));
    yc_number_node_ptr temp420 =
      2.08333333333333e-2 *
      ((temp330 * ti1 (x, y, z) + temp333 * ti3 (x, y, z)) * ti2 (x, y,
								  z) -
       (-4.16666666666667e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y, z - 1) +
	7.5e-2 * u (t, x, y,
		     z + 1) - 2.5e-2 * u (t,
					   x,
					   y,
					   z +
					   2)
	+ 4.16666666666667e-3 * u (t, x, y, z + 3)) * ti0 (x, y, z));
    yc_number_node_ptr temp387 =
      4.16666666666667e-3 * u (t, x, y, z) - 1.25e-2 * u (t, x - 4, y,
							    z) -
      4.16666666666667e-2 * u (t, x - 3, y, z) + 7.5e-2 * u (t, x - 2, y,
							       z) -
      2.5e-2 * u (t, x - 1, y, z);
    yc_number_node_ptr temp383 =
      3.33333333333333e-2 * (u (t, x, y, z) - u (t, x - 2, y, z)) +
      4.16666666666667e-3 * (u (t, x - 3, y, z) - u (t, x + 1, y, z));
    yc_number_node_ptr temp392 =
      4.16666666666667e-3 * (u (t, x - 2, y - 2, z) - u (t, x - 2, y + 2,
							  z)) +
      3.33333333333333e-2 * (-u (t, x - 2,
				  y - 1,
				  z) + u (t,
					  x - 2,
					  y + 1,
					  z));
    yc_number_node_ptr temp284 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y, z - 2) - v (t, x + 2, y, z - 2)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y, z - 2) +
				 v (t, x + 1, y, z - 2))) * ti1 (x, y,
								 z - 2) +
	(-4.16666666666667e-2 * v (t, x, y, z - 2) -
	 1.25e-2 * v (t, x, y - 1, z - 2) + 7.5e-2 * v (t, x, y + 1,
							  z - 2) -
	 2.5e-2 * v (t, x, y + 2, z - 2) + 4.16666666666667e-3 * v (t, x,
								      y + 3,
								      z -
								      2)) *
	ti3 (x, y, z - 2)) * ti0 (x, y, z - 2) + (-2.5e-2 * v (t, x, y,
								z) -
						  1.25e-2 * v (t, x, y,
								z - 3) -
						  4.16666666666667e-2 * v (t,
									    x,
									    y,
									    z
									    -
									    2)
						  + 7.5e-2 * v (t, x, y,
								 z - 1) +
						  4.16666666666667e-3 * v (t,
									    x,
									    y,
									    z
									    +
									    1))
       * ti2 (x, y, z - 2)) * ti2 (x, y, z - 2);
    yc_number_node_ptr temp308 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y - 2, z) - v (t, x + 2, y - 2, z)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y - 2, z) +
				 v (t, x + 1, y - 2, z))) * ti1 (x, y - 2,
								 z) +
	(-2.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x, y - 3, z) -
	 4.16666666666667e-2 * v (t, x, y - 2, z) + 7.5e-2 * v (t, x, y - 1,
								  z) +
	 4.16666666666667e-3 * v (t, x, y + 1, z)) * ti3 (x, y - 2,
							   z)) * ti0 (x,
								      y - 2,
								      z) +
       (-4.16666666666667e-2 * v (t, x, y - 2, z) -
	1.25e-2 * v (t, x, y - 2, z - 1) + 7.5e-2 * v (t, x, y - 2,
							 z + 1) -
	2.5e-2 * v (t, x, y - 2, z + 2) + 4.16666666666667e-3 * v (t, x,
								     y - 2,
								     z +
								     3)) *
       ti2 (x, y - 2, z)) * ti0 (x, y - 2, z) * ti3 (x, y - 2, z);
    yc_number_node_ptr temp92 =
      (((4.16666666666667e-3 *
	 (v (t, x, y - 2, z + 1) - v (t, x, y + 2, z + 1)) +
	 3.33333333333333e-2 * (-v (t, x, y - 1, z + 1) +
				 v (t, x, y + 1, z + 1))) * ti3 (x, y,
								 z + 1) +
	(-4.16666666666667e-2 * v (t, x, y, z + 1) -
	 1.25e-2 * v (t, x - 1, y, z + 1) + 7.5e-2 * v (t, x + 1, y,
							  z + 1) -
	 2.5e-2 * v (t, x + 2, y, z + 1) + 4.16666666666667e-3 * v (t,
								      x + 3,
								      y,
								      z +
								      1)) *
	ti1 (x, y, z + 1)) * ti0 (x, y,
				  z + 1) +
       (3.33333333333333e-2 * (-v (t, x, y, z) + v (t, x, y, z + 2)) +
	4.16666666666667e-3 * (v (t, x, y, z - 1) -
				v (t, x, y, z + 3))) * ti2 (x, y,
							    z + 1)) * ti2 (x,
									   y,
									   z +
									   1);
    yc_number_node_ptr temp185 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y - 2, z) - v (t, x - 2, y + 2, z)) +
	 3.33333333333333e-2 * (-v (t, x - 2, y - 1, z) +
				 v (t, x - 2, y + 1, z))) * ti3 (x - 2, y,
								 z) +
	(-2.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x - 3, y, z) -
	 4.16666666666667e-2 * v (t, x - 2, y, z) + 7.5e-2 * v (t, x - 1, y,
								  z) +
	 4.16666666666667e-3 * v (t, x + 1, y, z)) * ti1 (x - 2, y,
							   z)) * ti0 (x - 2,
								      y,
								      z) +
       (4.16666666666667e-3 *
	(v (t, x - 2, y, z - 2) - v (t, x - 2, y, z + 2)) +
	3.33333333333333e-2 * (-v (t, x - 2, y, z - 1) +
				v (t, x - 2, y, z + 1))) * ti2 (x - 2, y,
								z)) * ti0 (x -
									   2,
									   y,
									   z)
      * ti1 (x - 2, y, z);
    yc_number_node_ptr temp283 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y, z - 3) - v (t, x + 2, y, z - 3)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y, z - 3) +
				 v (t, x + 1, y, z - 3))) * ti1 (x, y,
								 z - 3) +
	(-4.16666666666667e-2 * v (t, x, y, z - 3) -
	 1.25e-2 * v (t, x, y - 1, z - 3) + 7.5e-2 * v (t, x, y + 1,
							  z - 3) -
	 2.5e-2 * v (t, x, y + 2, z - 3) + 4.16666666666667e-3 * v (t, x,
								      y + 3,
								      z -
								      3)) *
	ti3 (x, y, z - 3)) * ti0 (x, y, z - 3) + (4.16666666666667e-3 * v (t,
									    x,
									    y,
									    z) -
						  1.25e-2 * v (t, x, y,
								z - 4) -
						  4.16666666666667e-2 * v (t,
									    x,
									    y,
									    z -
									    3) +
						  7.5e-2 * v (t, x, y,
							       z - 2) -
						  2.5e-2 * v (t, x, y,
							       z - 1)) * ti2 (x,
									      y,
									      z
									      -
									      3))
      * ti2 (x, y, z - 3);
    yc_number_node_ptr temp309 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y - 1, z) - v (t, x + 2, y - 1, z)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y - 1, z) +
				 v (t, x + 1, y - 1, z))) * ti1 (x, y - 1,
								 z) +
	(7.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x, y - 2, z) -
	 4.16666666666667e-2 * v (t, x, y - 1, z) - 2.5e-2 * v (t, x, y + 1,
								  z) +
	 4.16666666666667e-3 * v (t, x, y + 2, z)) * ti3 (x, y - 1,
							   z)) * ti0 (x,
								      y - 1,
								      z) +
       (-4.16666666666667e-2 * v (t, x, y - 1, z) -
	1.25e-2 * v (t, x, y - 1, z - 1) + 7.5e-2 * v (t, x, y - 1,
							 z + 1) -
	2.5e-2 * v (t, x, y - 1, z + 2) + 4.16666666666667e-3 * v (t, x,
								     y - 1,
								     z +
								     3)) *
       ti2 (x, y - 1, z)) * ti0 (x, y - 1, z) * ti3 (x, y - 1, z);
    yc_number_node_ptr temp310 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y + 1, z) - v (t, x + 2, y + 1, z)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y + 1, z) +
				 v (t, x + 1, y + 1, z))) * ti1 (x, y + 1,
								 z) +
	(-1.25e-2 * v (t, x, y, z) -
	 4.16666666666667e-2 * v (t, x, y + 1, z) + 7.5e-2 * v (t, x, y + 2,
								  z) -
	 2.5e-2 * v (t, x, y + 3, z) + 4.16666666666667e-3 * v (t, x, y + 4,
								  z)) * ti3 (x,
									     y +
									     1,
									     z))
       * ti0 (x, y + 1,
	      z) + (-4.16666666666667e-2 * v (t, x,
					       y + 1,
					       z) - 1.25e-2 * v (t, x, y + 1,
								  z - 1) +
		    7.5e-2 * v (t,
				 x,
				 y + 1,
				 z + 1) - 2.5e-2 * v (t, x, y + 1,
						       z + 2) +
		    4.16666666666667e-3 * v (t, x, y + 1,
					      z + 3)) * ti2 (x, y + 1,
							     z)) * ti0 (x,
									y + 1,
									z) *
      ti3 (x, y + 1, z);
    yc_number_node_ptr temp307 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y - 3, z) - v (t, x + 2, y - 3, z)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y - 3, z) +
				 v (t, x + 1, y - 3, z))) * ti1 (x, y - 3,
								 z) +
	(4.16666666666667e-3 * v (t, x, y, z) - 1.25e-2 * v (t, x, y - 4, z) -
	 4.16666666666667e-2 * v (t, x,
				   y - 3,
				   z) +
	 7.5e-2 * v (t, x, y - 2, z) - 2.5e-2 * v (t, x, y - 1,
						     z)) * ti3 (x, y - 3,
								z)) * ti0 (x,
									   y -
									   3,
									   z) +
       (-4.16666666666667e-2 * v (t, x, y - 3, z) -
	1.25e-2 * v (t, x, y - 3, z - 1) + 7.5e-2 * v (t, x, y - 3,
							 z + 1) -
	2.5e-2 * v (t, x, y - 3, z + 2) + 4.16666666666667e-3 * v (t, x,
								     y - 3,
								     z +
								     3)) *
       ti2 (x, y - 3, z)) * ti0 (x, y - 3, z) * ti3 (x, y - 3, z);
    yc_number_node_ptr temp298 =
      (((4.16666666666667e-3 * (v (t, x, y, z) - v (t, x + 4, y, z)) +
	 3.33333333333333e-2 * (-v (t, x + 1, y, z) +
				 v (t, x + 3, y, z))) * ti1 (x + 2, y,
							     z) +
	(-4.16666666666667e-2 * v (t, x + 2, y, z) -
	 1.25e-2 * v (t, x + 2, y - 1, z) + 7.5e-2 * v (t, x + 2, y + 1,
							  z) - 2.5e-2 * v (t,
									    x +
									    2,
									    y +
									    2,
									    z) +
	 4.16666666666667e-3 * v (t, x + 2, y + 3, z)) * ti3 (x + 2, y,
							       z)) * ti0 (x + 2,
									  y,
									  z) +
       (-4.16666666666667e-2 * v (t, x + 2, y,
				   z) - 1.25e-2 * v (t, x + 2, y,
						      z - 1) +
	7.5e-2 * v (t, x + 2, y, z + 1) - 2.5e-2 * v (t, x + 2, y,
							z + 2) +
	4.16666666666667e-3 * v (t, x + 2, y, z + 3)) * ti2 (x + 2,
							      y,
							      z)) * ti0 (x + 2,
									 y,
									 z) *
      ti1 (x + 2, y, z);
    yc_number_node_ptr temp165 =
      (((4.16666666666667e-3 *
	 (v (t, x - 3, y - 2, z) - v (t, x - 3, y + 2, z)) +
	 3.33333333333333e-2 * (-v (t, x - 3, y - 1, z) +
				 v (t, x - 3, y + 1, z))) * ti3 (x - 3, y,
								 z) +
	(4.16666666666667e-3 * v (t, x, y, z) - 1.25e-2 * v (t, x - 4, y, z) -
	 4.16666666666667e-2 * v (t, x - 3,
				   y,
				   z) +
	 7.5e-2 * v (t, x - 2, y, z) - 2.5e-2 * v (t, x - 1, y,
						     z)) * ti1 (x - 3, y,
								z)) * ti0 (x -
									   3,
									   y,
									   z)
       +
       (4.16666666666667e-3 *
	(v (t, x - 3, y, z - 2) - v (t, x - 3, y, z + 2)) +
	3.33333333333333e-2 * (-v (t, x - 3, y, z - 1) +
				v (t, x - 3, y, z + 1))) * ti2 (x - 3, y,
								z)) * ti0 (x -
									   3,
									   y,
									   z)
      * ti1 (x - 3, y, z);
    yc_number_node_ptr temp154 =
      (((4.16666666666667e-3 *
	 (v (t, x, y - 2, z - 1) - v (t, x, y + 2, z - 1)) +
	 3.33333333333333e-2 * (-v (t, x, y - 1, z - 1) +
				 v (t, x, y + 1, z - 1))) * ti3 (x, y,
								 z - 1) +
	(-4.16666666666667e-2 * v (t, x, y, z - 1) -
	 1.25e-2 * v (t, x - 1, y, z - 1) + 7.5e-2 * v (t, x + 1, y,
							  z - 1) -
	 2.5e-2 * v (t, x + 2, y, z - 1) + 4.16666666666667e-3 * v (t,
								      x + 3,
								      y,
								      z -
								      1)) *
	ti1 (x, y, z - 1)) * ti0 (x, y,
				  z - 1) +
       (3.33333333333333e-2 * (v (t, x, y, z) - v (t, x, y, z - 2)) +
	4.16666666666667e-3 * (v (t, x, y, z - 3) -
				v (t, x, y, z + 1))) * ti2 (x, y,
							    z - 1)) * ti2 (x,
									   y,
									   z -
									   1);
    yc_number_node_ptr temp299 =
      (((3.33333333333333e-2 * (v (t, x, y, z) - v (t, x - 2, y, z)) +
	 4.16666666666667e-3 * (v (t, x - 3, y, z) -
				 v (t, x + 1, y, z))) * ti1 (x - 1, y,
							     z) +
	(-4.16666666666667e-2 * v (t, x - 1, y, z) -
	 1.25e-2 * v (t, x - 1, y - 1, z) + 7.5e-2 * v (t, x - 1, y + 1,
							  z) - 2.5e-2 * v (t,
									    x -
									    1,
									    y +
									    2,
									    z) +
	 4.16666666666667e-3 * v (t, x - 1, y + 3, z)) * ti3 (x - 1, y,
							       z)) * ti0 (x - 1,
									  y,
									  z) +
       (-4.16666666666667e-2 * v (t, x - 1, y,
				   z) - 1.25e-2 * v (t, x - 1, y,
						      z - 1) +
	7.5e-2 * v (t, x - 1, y, z + 1) - 2.5e-2 * v (t, x - 1, y,
							z + 2) +
	4.16666666666667e-3 * v (t, x - 1, y, z + 3)) * ti2 (x - 1,
							      y,
							      z)) * ti0 (x - 1,
									 y,
									 z) *
      ti1 (x - 1, y, z);
    yc_number_node_ptr temp289 =
      (((3.33333333333333e-2 * (-v (t, x, y, z) + v (t, x + 2, y, z)) +
	 4.16666666666667e-3 * (v (t, x - 1, y, z) -
				 v (t, x + 3, y, z))) * ti1 (x + 1, y,
							     z) +
	(-4.16666666666667e-2 * v (t, x + 1, y, z) -
	 1.25e-2 * v (t, x + 1, y - 1, z) + 7.5e-2 * v (t, x + 1, y + 1,
							  z) - 2.5e-2 * v (t,
									    x +
									    1,
									    y +
									    2,
									    z) +
	 4.16666666666667e-3 * v (t, x + 1, y + 3, z)) * ti3 (x + 1, y,
							       z)) * ti0 (x + 1,
									  y,
									  z) +
       (-4.16666666666667e-2 * v (t, x + 1, y,
				   z) - 1.25e-2 * v (t, x + 1, y,
						      z - 1) +
	7.5e-2 * v (t, x + 1, y, z + 1) - 2.5e-2 * v (t, x + 1, y,
							z + 2) +
	4.16666666666667e-3 * v (t, x + 1, y, z + 3)) * ti2 (x + 1,
							      y,
							      z)) * ti0 (x + 1,
									 y,
									 z) *
      ti1 (x + 1, y, z);
    yc_number_node_ptr temp116 =
      (((4.16666666666667e-3 *
	 (v (t, x, y - 2, z - 2) - v (t, x, y + 2, z - 2)) +
	 3.33333333333333e-2 * (-v (t, x, y - 1, z - 2) +
				 v (t, x, y + 1, z - 2))) * ti3 (x, y,
								 z - 2) +
	(-4.16666666666667e-2 * v (t, x, y, z - 2) -
	 1.25e-2 * v (t, x - 1, y, z - 2) + 7.5e-2 * v (t, x + 1, y,
							  z - 2) -
	 2.5e-2 * v (t, x + 2, y, z - 2) + 4.16666666666667e-3 * v (t,
								      x + 3,
								      y,
								      z -
								      2)) *
	ti1 (x, y, z - 2)) * ti0 (x, y,
				  z - 2) +
       (4.16666666666667e-3 * (-v (t, x, y, z) + v (t, x, y, z - 4)) +
	3.33333333333333e-2 * (-v (t, x, y, z - 3) +
				v (t, x, y, z - 1))) * ti2 (x, y,
							    z - 2)) * ti2 (x,
									   y,
									   z -
									   2);
    yc_number_node_ptr temp56 =
      (((4.16666666666667e-3 * (v (t, x, y - 2, z) - v (t, x, y + 2, z)) +
	 3.33333333333333e-2 * (-v (t, x, y - 1, z) +
				 v (t, x, y + 1, z))) * ti3 (x, y,
							     z) +
	(-4.16666666666667e-2 * v (t, x, y, z) -
	 1.25e-2 * v (t, x - 1, y, z) + 7.5e-2 * v (t, x + 1, y,
						      z) - 2.5e-2 * v (t,
									x + 2,
									y,
									z) +
	 4.16666666666667e-3 * v (t, x + 3, y, z)) * ti1 (x, y, z)) * ti0 (x,
									    y,
									    z)
       + (4.16666666666667e-3 * (v (t, x, y, z - 2) - v (t, x, y, z + 2)) +
	  3.33333333333333e-2 * (-v (t, x, y, z - 1) +
				  v (t, x, y, z + 1))) * ti2 (x, y,
							      z)) * ti0 (x, y,
									 z) *
      ti1 (x, y, z);
    yc_number_node_ptr temp204 =
      (((4.16666666666667e-3 *
	 (v (t, x - 1, y - 2, z) - v (t, x - 1, y + 2, z)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y - 1, z) +
				 v (t, x - 1, y + 1, z))) * ti3 (x - 1, y,
								 z) +
	(7.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x - 2, y, z) -
	 4.16666666666667e-2 * v (t, x - 1, y, z) - 2.5e-2 * v (t, x + 1, y,
								  z) +
	 4.16666666666667e-3 * v (t, x + 2, y, z)) * ti1 (x - 1, y,
							   z)) * ti0 (x - 1,
								      y,
								      z) +
       (4.16666666666667e-3 *
	(v (t, x - 1, y, z - 2) - v (t, x - 1, y, z + 2)) +
	3.33333333333333e-2 * (-v (t, x - 1, y, z - 1) +
				v (t, x - 1, y, z + 1))) * ti2 (x - 1, y,
								z)) * ti0 (x -
									   1,
									   y,
									   z)
      * ti1 (x - 1, y, z);
    yc_number_node_ptr temp288 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y, z + 1) - v (t, x + 2, y, z + 1)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y, z + 1) +
				 v (t, x + 1, y, z + 1))) * ti1 (x, y,
								 z + 1) +
	(-4.16666666666667e-2 * v (t, x, y, z + 1) -
	 1.25e-2 * v (t, x, y - 1, z + 1) + 7.5e-2 * v (t, x, y + 1,
							  z + 1) -
	 2.5e-2 * v (t, x, y + 2, z + 1) + 4.16666666666667e-3 * v (t, x,
								      y + 3,
								      z +
								      1)) *
	ti3 (x, y, z + 1)) * ti0 (x, y, z + 1) + (-1.25e-2 * v (t, x, y,
								 z) -
						  4.16666666666667e-2 * v (t,
									    x,
									    y,
									    z
									    +
									    1)
						  + 7.5e-2 * v (t, x, y,
								 z + 2) -
						  2.5e-2 * v (t, x, y,
							       z + 3) +
						  4.16666666666667e-3 * v (t,
									    x,
									    y,
									    z
									    +
									    4))
       * ti2 (x, y, z + 1)) * ti2 (x, y, z + 1);
    yc_number_node_ptr temp10 =
      8.85879567828298e-1 * damp (x, y, z) - 2.0 * m (x, y, z);
    yc_number_node_ptr temp133 =
      (((4.16666666666667e-3 *
	 (v (t, x, y - 2, z + 2) - v (t, x, y + 2, z + 2)) +
	 3.33333333333333e-2 * (-v (t, x, y - 1, z + 2) +
				 v (t, x, y + 1, z + 2))) * ti3 (x, y,
								 z + 2) +
	(-4.16666666666667e-2 * v (t, x, y, z + 2) -
	 1.25e-2 * v (t, x - 1, y, z + 2) + 7.5e-2 * v (t, x + 1, y,
							  z + 2) -
	 2.5e-2 * v (t, x + 2, y, z + 2) + 4.16666666666667e-3 * v (t,
								      x + 3,
								      y,
								      z +
								      2)) *
	ti1 (x, y, z + 2)) * ti0 (x, y,
				  z + 2) +
       (4.16666666666667e-3 * (v (t, x, y, z) - v (t, x, y, z + 4)) +
	3.33333333333333e-2 * (-v (t, x, y, z + 1) +
				v (t, x, y, z + 3))) * ti2 (x, y,
							    z + 2)) * ti2 (x,
									   y,
									   z +
									   2);
    yc_number_node_ptr temp286 =
      (((4.16666666666667e-3 *
	 (v (t, x - 2, y, z - 1) - v (t, x + 2, y, z - 1)) +
	 3.33333333333333e-2 * (-v (t, x - 1, y, z - 1) +
				 v (t, x + 1, y, z - 1))) * ti1 (x, y,
								 z - 1) +
	(-4.16666666666667e-2 * v (t, x, y, z - 1) -
	 1.25e-2 * v (t, x, y - 1, z - 1) + 7.5e-2 * v (t, x, y + 1,
							  z - 1) -
	 2.5e-2 * v (t, x, y + 2, z - 1) + 4.16666666666667e-3 * v (t, x,
								      y + 3,
								      z -
								      1)) *
	ti3 (x, y, z - 1)) * ti0 (x, y, z - 1) + (7.5e-2 * v (t, x, y,
							       z) -
						  1.25e-2 * v (t, x, y,
								z - 2) -
						  4.16666666666667e-2 * v (t,
									    x,
									    y,
									    z
									    -
									    1)
						  - 2.5e-2 * v (t, x, y,
								 z + 1) +
						  4.16666666666667e-3 * v (t,
									    x,
									    y,
									    z
									    +
									    2))
       * ti2 (x, y, z - 1)) * ti2 (x, y, z - 1);
    yc_number_node_ptr temp252 =
      (((4.16666666666667e-3 * (-v (t, x, y, z) + v (t, x, y - 4, z)) +
	 3.33333333333333e-2 * (-v (t, x, y - 3, z) +
				 v (t, x, y - 1, z))) * ti3 (x, y - 2,
							     z) +
	(-4.16666666666667e-2 * v (t, x, y - 2, z) -
	 1.25e-2 * v (t, x - 1, y - 2, z) + 7.5e-2 * v (t, x + 1, y - 2,
							  z) - 2.5e-2 * v (t,
									    x +
									    2,
									    y -
									    2,
									    z) +
	 4.16666666666667e-3 * v (t, x + 3, y - 2, z)) * ti1 (x, y - 2,
							       z)) * ti0 (x,
									  y - 2,
									  z)
       +
       (4.16666666666667e-3 *
	(v (t, x, y - 2, z - 2) - v (t, x, y - 2, z + 2)) +
	3.33333333333333e-2 * (-v (t, x, y - 2, z - 1) +
				v (t, x, y - 2, z + 1))) * ti2 (x, y - 2,
								z)) * ti0 (x,
									   y -
									   2,
									   z) *
      ti3 (x, y - 2, z);
    yc_number_node_ptr temp487 = temp420 * ti2 (x, y, z) * ti3 (x, y,
						       z) +
      2.08333333333333e-2 *
      ((-temp318 * ti1 (x, y, z) + temp325 * ti3 (x, y, z)) * ti3 (x, y,
								   z) +
       ((temp318 * ti3 (x, y, z) + temp325 * ti1 (x, y, z)) * ti2 (x, y,
								   z) -
	(4.16666666666667e-3 * (u (t, x, y, z - 2) - u (t, x, y, z + 2)) +
	 3.33333333333333e-2 * (-u (t, x, y, z - 1) +
				 u (t, x, y, z + 1))) * ti0 (x, y,
							     z)) * ti1 (x,
									y,
									z)
       * ti2 (x, y,
	      z)) + 3.75e-2 * ((temp399 * ti3 (x, y - 1, z) - temp401 * ti1 (x,
									      y
									      -
									      1,
									      z))
				* ti1 (x, y - 1,
				       z) +
				(((4.16666666666667e-3 *
				   (u (t, x - 2, y, z - 1) - u (t, x + 2, y,
								z - 1)) +
				   3.33333333333333e-2 * (-u (t,
							       x - 1,
							       y,
							       z - 1) + u (t,
									   x +
									   1,
									   y,
									   z -
									   1)))
				  * ti1 (x, y,
					 z - 1) + (-4.16666666666667e-2 * u (t,
									      x,
									      y,
									      z
									      -
									      1)
						   - 1.25e-2 * u (t, x, y - 1,
								   z - 1) +
						   7.5e-2 * u (t, x, y + 1,
								z - 1) -
						   2.5e-2 * u (t, x, y + 2,
								z - 1) +
						   4.16666666666667e-3 * u (t,
									     x,
									     y +
									     3,
									     z -
									     1))
				  * ti3 (x, y, z - 1)) * ti2 (x, y,
							      z - 1) -
				 (7.5e-2 * u (t, x, y, z) -
				  1.25e-2 * u (t, x, y,
						z - 2) -
				  4.16666666666667e-2 * u (t, x, y,
							    z - 1) -
				  2.5e-2 * u (t, x, y,
					       z + 1) +
				  4.16666666666667e-3 * u (t, x, y,
							    z + 2)) * ti0 (x, y,
									   z -
									   1)) *
				ti0 (x, y,
				     z - 1)) + 1.25e-2 * ((-temp392 * ti1 (x -
									    2,
									    y,
									    z) +
							    temp394 * ti3 (x -
									   2, y,
									   z)) *
							   ti3 (x - 2, y,
								z) +
							   ((temp392 *
							     ti3 (x - 2, y,
								  z) +
							     temp394 * ti1 (x -
									    2,
									    y,
									    z))
							    * ti2 (x - 2, y,
								   z) -
							    (4.16666666666667e-3
							     * (u (t, x - 2, y,
								   z - 2) -
								u (t,
								   x - 2, y,
								   z +
								   2)) +
							     3.33333333333333e-2
							     * (-u (t, x - 2, y,
								    z - 1) +
								u (t,
								   x - 2, y,
								   z +
								   1)))
							    * ti0 (x - 2, y,
								   z)) *
							   ti1 (x - 2, y,
								z) * ti2 (x - 2,
									  y,
									  z) +
							   ((temp395 *
							     ti1 (x, y - 2,
								  z) +
							     temp396 * ti3 (x,
									    y -
									    2,
									    z))
							    * ti2 (x, y - 2,
								   z) -
							    (-4.16666666666667e-2
							     * u (t, x, y - 2,
								  z) -
							     1.25e-2 * u (t, x,
									   y -
									   2,
									   z -
									   1) +
							     7.5e-2 * u (t, x,
									  y - 2,
									  z +
									  1) -
							     2.5e-2 * u (t, x,
									  y - 2,
									  z +
									  2) +
							     4.16666666666667e-3
							     * u (t, x, y - 2,
								  z +
								  3)) * ti0 (x,
									     y -
									     2,
									     z))
							   * ti2 (x, y - 2,
								  z) * ti3 (x,
									    y -
									    2,
									    z))
      +
      6.25e-3 * ((-temp409 * ti1 (x + 1, y, z) + temp410 * ti3 (x + 1, y, z)) *
		  ti3 (x + 1,
		       y,
		       z)
		  +
		  ((temp404 * ti1 (x, y + 1, z) +
		    temp406 * ti3 (x, y + 1, z)) * ti2 (x,
							y + 1,
							z)
		   - (-4.16666666666667e-2 * u (t, x, y + 1, z) -
		      1.25e-2 * u (t, x, y + 1, z - 1) + 7.5e-2 * u (t, x,
								       y + 1,
								       z + 1) -
		      2.5e-2 * u (t, x, y + 1,
				   z + 2) + 4.16666666666667e-3 * u (t, x,
								      y + 1,
								      z +
								      3)) *
		   ti0 (x, y + 1, z)) * ti2 (x, y + 1, z) * ti3 (x, y + 1,
								 z) +
		  ((temp409 * ti3 (x + 1, y, z) +
		    temp410 * ti1 (x + 1, y, z)) * ti2 (x + 1,
							y,
							z)
		   -
		   (4.16666666666667e-3 *
		    (u (t, x + 1, y, z - 2) - u (t, x + 1, y, z + 2)) +
		    3.33333333333333e-2 * (-u (t, x + 1, y, z - 1) +
					    u (t, x + 1, y,
					       z + 1))) * ti0 (x + 1, y,
							       z)) * ti1 (x + 1,
									  y,
									  z) *
		  ti2 (x + 1, y,
		       z)) +
      1.66666666666667e-2 *
      ((temp343 * ti3 (x + 1, y, z) - temp347 * ti1 (x + 1, y, z)) * ti3 (x + 1,
									  y,
									  z) +
       (-temp377 * ti1 (x, y - 1, z) + temp381 * ti3 (x, y - 1, z)) * ti1 (x,
									   y -
									   1,
									   z) +
       ((temp336 * ti3 (x, y + 1, z) + temp342 * ti1 (x, y + 1, z)) * ti2 (x,
									   y +
									   1,
									   z) -
	(4.16666666666667e-3 *
	 (u (t, x, y + 1, z - 2) - u (t, x, y + 1, z + 2)) +
	 3.33333333333333e-2 * (-u (t, x, y + 1, z - 1) +
				 u (t, x, y + 1, z + 1))) * ti0 (x, y + 1,
								 z)) * ti2 (x,
									    y +
									    1,
									    z) *
       ti3 (x, y + 1,
	    z) +
       ((temp343 * ti1 (x + 1, y, z) + temp347 * ti3 (x + 1, y, z)) * ti2 (x +
									   1, y,
									   z) -
	(-4.16666666666667e-2 * u (t, x + 1, y, z) -
	 1.25e-2 * u (t, x + 1, y, z - 1) + 7.5e-2 * u (t,
							  x + 1,
							  y,
							  z + 1) -
	 2.5e-2 * u (t, x + 1, y,
		      z + 2) + 4.16666666666667e-3 * u (t, x + 1,
							 y,
							 z +
							 3)) *
	ti0 (x + 1, y, z)) * ti1 (x + 1, y, z) * ti2 (x + 1, y,
						      z) +
       (((4.16666666666667e-3 *
	  (u (t, x, y - 2, z - 1) - u (t, x, y + 2, z - 1)) +
	  3.33333333333333e-2 * (-u (t, x, y - 1, z - 1) +
				  u (t, x, y + 1, z - 1))) * ti3 (x, y,
								  z - 1) +
	 (-4.16666666666667e-2 * u (t, x, y, z - 1) -
	  1.25e-2 * u (t, x - 1, y, z - 1) + 7.5e-2 * u (t, x + 1, y,
							   z - 1) -
	  2.5e-2 * u (t, x + 2, y, z - 1) + 4.16666666666667e-3 * u (t,
								       x + 3,
								       y,
								       z -
								       1))
	 * ti1 (x, y, z - 1)) * ti2 (x, y,
				     z - 1) -
	(3.33333333333333e-2 * (u (t, x, y, z) - u (t, x, y,
						     z - 2)) +
	 4.16666666666667e-3 * (u (t, x, y, z - 3) - u (t, x, y,
							 z + 1))) * ti0 (x, y,
									 z -
									 1)) *
       ti0 (x,
	    y,
	    z
	    -
	    1))
      +
      2.08333333333333e-3 *
      ((temp360 * ti3 (x - 2, y, z) - temp365 * ti1 (x - 2, y, z)) * ti3 (x - 2,
									  y,
									  z) +
       (-temp367 * ti1 (x, y + 2, z) + temp370 * ti3 (x, y + 2, z)) * ti1 (x,
									   y +
									   2,
									   z) +
       (temp388 * ti3 (x, y - 3, z) - temp390 * ti1 (x, y - 3, z)) * ti1 (x,
									  y - 3,
									  z)
       + ((temp352 * ti3 (x, y - 2, z) + temp357 * ti1 (x, y - 2, z)) * ti2 (x,
									     y -
									     2,
									     z)
	  -
	  (4.16666666666667e-3 *
	   (u (t, x, y - 2, z - 2) - u (t, x, y - 2, z + 2)) +
	   3.33333333333333e-2 * (-u (t, x, y - 2, z - 1) +
				   u (t, x, y - 2, z + 1))) * ti0 (x, y - 2,
								   z)) * ti2 (x,
									      y
									      -
									      2,
									      z)
       * ti3 (x, y - 2,
	      z) +
       ((temp360 * ti1 (x - 2, y, z) + temp365 * ti3 (x - 2, y, z)) * ti2 (x -
									   2, y,
									   z) -
	(-4.16666666666667e-2 * u (t, x - 2, y, z) -
	 1.25e-2 * u (t, x - 2, y, z - 1) + 7.5e-2 * u (t,
							  x - 2,
							  y,
							  z + 1) -
	 2.5e-2 * u (t, x - 2, y,
		      z + 2) + 4.16666666666667e-3 * u (t, x - 2,
							 y,
							 z +
							 3)) *
	ti0 (x - 2, y, z)) * ti1 (x - 2, y, z) * ti2 (x - 2, y,
						      z) +
       (((4.16666666666667e-3 *
	  (u (t, x, y - 2, z + 2) - u (t, x, y + 2, z + 2)) +
	  3.33333333333333e-2 * (-u (t, x, y - 1, z + 2) +
				  u (t, x, y + 1, z + 2))) * ti3 (x, y,
								  z + 2) +
	 (-4.16666666666667e-2 * u (t, x, y, z + 2) -
	  1.25e-2 * u (t, x - 1, y, z + 2) + 7.5e-2 * u (t, x + 1, y,
							   z + 2) -
	  2.5e-2 * u (t, x + 2, y, z + 2) + 4.16666666666667e-3 * u (t,
								       x + 3,
								       y,
								       z +
								       2)) *
	 ti1 (x, y, z + 2)) * ti2 (x, y,
				   z + 2) -
	(4.16666666666667e-3 * (u (t, x, y, z) - u (t, x, y, z + 4)) +
	 3.33333333333333e-2 * (-u (t, x, y, z + 1) +
				 u (t, x, y, z + 3))) * ti0 (x, y,
							     z + 2)) * ti0 (x,
									    y,
									    z
									    +
									    2)
       +
       (((4.16666666666667e-3 *
	  (u (t, x - 2, y, z - 3) - u (t, x + 2, y, z - 3)) +
	  3.33333333333333e-2 * (-u (t, x - 1, y, z - 3) +
				  u (t, x + 1, y, z - 3))) * ti1 (x, y,
								  z - 3) +
	 (-4.16666666666667e-2 * u (t, x, y, z - 3) -
	  1.25e-2 * u (t, x, y - 1, z - 3) + 7.5e-2 * u (t, x, y + 1,
							   z - 3) -
	  2.5e-2 * u (t, x, y + 2, z - 3) + 4.16666666666667e-3 * u (t, x,
								       y + 3,
								       z -
								       3)) *
	 ti3 (x, y, z - 3)) * ti2 (x, y,
				   z - 3) - (4.16666666666667e-3 * u (t, x,
								       y,
								       z) -
					     1.25e-2 * u (t, x, y,
							   z - 4) -
					     4.16666666666667e-2 * u (t, x,
								       y,
								       z -
								       3) +
					     7.5e-2 * u (t, x, y,
							  z - 2) -
					     2.5e-2 * u (t, x, y,
							  z - 1)) * ti0 (x,
									 y,
									 z -
									 3))
       * ti0 (x, y, z - 3)) - (temp420 * ti0 (x, y,
					      z) +
			       2.08333333333333e-2 * (temp330 * ti3 (x, y, z) -
						       temp333 * ti1 (x, y,
								      z)) *
			       ti1 (x, y,
				    z) +
			       1.66666666666667e-2 * (-temp336 * ti1 (x, y + 1,
								       z) +
						       temp342 * ti3 (x, y + 1,
								      z)) *
			       ti1 (x, y + 1,
				    z) +
			       2.08333333333333e-3 * (-temp352 * ti1 (x, y - 2,
								       z) +
						       temp357 * ti3 (x, y - 2,
								      z)) *
			       ti1 (x, y - 2,
				    z) +
			       2.08333333333333e-3 * (temp372 * ti3 (x + 2, y,
								      z) -
						       temp375 * ti1 (x + 2, y,
								      z)) *
			       ti3 (x + 2, y,
				    z) +
			       1.66666666666667e-2 * (temp383 * ti3 (x - 1, y,
								      z) -
						       temp385 * ti1 (x - 1, y,
								      z)) *
			       ti3 (x - 1, y,
				    z) +
			       2.08333333333333e-3 * (-temp386 * ti1 (x - 3, y,
								       z) +
						       temp387 * ti3 (x - 3, y,
								      z)) *
			       ti3 (x - 3, y,
				    z) + 1.25e-2 * (temp395 * ti3 (x, y - 2,
								    z) -
						     temp396 * ti1 (x, y - 2,
								    z)) *
			       ti1 (x, y - 2,
				    z) + 6.25e-3 * (temp404 * ti3 (x, y + 1,
								    z) -
						     temp406 * ti1 (x, y + 1,
								    z)) *
			       ti1 (x, y + 1,
				    z) + 3.75e-2 * (-temp407 * ti1 (x - 1, y,
								     z) +
						     temp408 * ti3 (x - 1, y,
								    z)) *
			       ti3 (x - 1, y,
				    z) +
			       2.08333333333333e-3 *
			       ((temp367 * ti3 (x, y + 2, z) +
				 temp370 * ti1 (x, y + 2, z)) * ti2 (x, y + 2,
								     z) -
				(4.16666666666667e-3 *
				 (u (t, x, y + 2, z - 2) - u (t, x, y + 2,
							      z + 2)) +
				 3.33333333333333e-2 * (-u (t, x,
							     y + 2,
							     z - 1) + u (t, x,
									 y + 2,
									 z +
									 1))) *
				ti0 (x, y + 2, z)) * ti2 (x, y + 2, z) * ti3 (x,
									      y
									      +
									      2,
									      z)
			       +
			       2.08333333333333e-3 *
			       ((temp372 * ti1 (x + 2, y, z) +
				 temp375 * ti3 (x + 2, y, z)) * ti2 (x + 2, y,
								     z) -
				(-4.16666666666667e-2 * u (t, x + 2, y, z) -
				 1.25e-2 * u (t, x + 2, y,
					       z - 1) + 7.5e-2 * u (t, x + 2,
								     y,
								     z + 1) -
				 2.5e-2 * u (t, x + 2, y,
					      z + 2) +
				 4.16666666666667e-3 * u (t, x + 2, y,
							   z + 3)) * ti0 (x + 2,
									  y,
									  z))
			       * ti1 (x + 2, y, z) * ti2 (x + 2, y,
							  z) +
			       1.66666666666667e-2 *
			       ((temp377 * ti3 (x, y - 1, z) +
				 temp381 * ti1 (x, y - 1, z)) * ti2 (x, y - 1,
								     z) -
				(4.16666666666667e-3 *
				 (u (t, x, y - 1, z - 2) - u (t, x, y - 1,
							      z + 2)) +
				 3.33333333333333e-2 * (-u (t, x,
							     y - 1,
							     z - 1) + u (t, x,
									 y - 1,
									 z +
									 1))) *
				ti0 (x, y - 1, z)) * ti2 (x, y - 1, z) * ti3 (x,
									      y
									      -
									      1,
									      z)
			       +
			       1.66666666666667e-2 *
			       ((temp383 * ti1 (x - 1, y, z) +
				 temp385 * ti3 (x - 1, y, z)) * ti2 (x - 1, y,
								     z) -
				(-4.16666666666667e-2 * u (t, x - 1, y, z) -
				 1.25e-2 * u (t, x - 1, y,
					       z - 1) + 7.5e-2 * u (t, x - 1,
								     y,
								     z + 1) -
				 2.5e-2 * u (t, x - 1, y,
					      z + 2) +
				 4.16666666666667e-3 * u (t, x - 1, y,
							   z + 3)) * ti0 (x - 1,
									  y,
									  z))
			       * ti1 (x - 1, y, z) * ti2 (x - 1, y,
							  z) +
			       2.08333333333333e-3 *
			       ((temp386 * ti3 (x - 3, y, z) +
				 temp387 * ti1 (x - 3, y, z)) * ti2 (x - 3, y,
								     z) -
				(4.16666666666667e-3 *
				 (u (t, x - 3, y, z - 2) - u (t, x - 3, y,
							      z + 2)) +
				 3.33333333333333e-2 * (-u (t,
							     x - 3, y,
							     z - 1) + u (t,
									 x - 3,
									 y,
									 z +
									 1))) *
				ti0 (x - 3, y, z)) * ti1 (x - 3, y,
							  z) * ti2 (x - 3, y,
								    z) +
			       2.08333333333333e-3 *
			       ((temp388 * ti1 (x, y - 3, z) +
				 temp390 * ti3 (x, y - 3, z)) * ti2 (x, y - 3,
								     z) -
				(-4.16666666666667e-2 * u (t, x, y - 3, z) -
				 1.25e-2 * u (t, x, y - 3,
					       z - 1) + 7.5e-2 * u (t, x,
								     y - 3,
								     z + 1) -
				 2.5e-2 * u (t, x, y - 3,
					      z + 2) +
				 4.16666666666667e-3 * u (t, x, y - 3,
							   z + 3)) * ti0 (x,
									  y - 3,
									  z))
			       * ti2 (x, y - 3, z) * ti3 (x, y - 3,
							  z) +
			       3.75e-2 *
			       ((temp399 * ti1 (x, y - 1, z) +
				 temp401 * ti3 (x, y - 1, z)) * ti2 (x, y - 1,
								     z) -
				(-4.16666666666667e-2 * u (t, x, y - 1, z) -
				 1.25e-2 * u (t, x, y - 1,
					       z - 1) + 7.5e-2 * u (t, x,
								     y - 1,
								     z + 1) -
				 2.5e-2 * u (t, x, y - 1,
					      z + 2) +
				 4.16666666666667e-3 * u (t, x, y - 1,
							   z + 3)) * ti0 (x,
									  y - 1,
									  z))
			       * ti2 (x, y - 1, z) * ti3 (x, y - 1,
							  z) +
			       3.75e-2 *
			       ((temp407 * ti3 (x - 1, y, z) +
				 temp408 * ti1 (x - 1, y, z)) * ti2 (x - 1, y,
								     z) -
				(4.16666666666667e-3 *
				 (u (t, x - 1, y, z - 2) - u (t, x - 1, y,
							      z + 2)) +
				 3.33333333333333e-2 * (-u (t,
							     x - 1, y,
							     z - 1) + u (t,
									 x - 1,
									 y,
									 z +
									 1))) *
				ti0 (x - 1, y, z)) * ti1 (x - 1, y,
							  z) * ti2 (x - 1, y,
								    z) +
			       2.08333333333333e-3 *
			       (((4.16666666666667e-3 *
				  (u (t, x, y - 2, z - 2) - u (t, x, y + 2,
							       z - 2)) +
				  3.33333333333333e-2 * (-u (t,
							      x,
							      y - 1,
							      z - 2) + u (t, x,
									  y + 1,
									  z -
									  2))) *
				 ti3 (x, y,
				      z - 2) + (-4.16666666666667e-2 * u (t,
									   x,
									   y,
									   z -
									   2) -
						1.25e-2 * u (t, x - 1, y,
							      z - 2) +
						7.5e-2 * u (t, x + 1, y,
							     z - 2) -
						2.5e-2 * u (t, x + 2, y,
							     z - 2) +
						4.16666666666667e-3 * u (t,
									  x + 3,
									  y,
									  z -
									  2))
				 * ti1 (x, y, z - 2)) * ti2 (x, y,
							     z - 2) -
				(4.16666666666667e-3 *
				 (-u (t, x, y, z) + u (t, x, y, z - 4)) +
				 3.33333333333333e-2 * (-u (t, x, y, z - 3) +
							 u (t, x, y,
							    z - 1))) * ti0 (x,
									    y,
									    z -
									    2))
			       * ti0 (x, y,
				      z - 2) +
			       1.66666666666667e-2 *
			       (((4.16666666666667e-3 *
				  (u (t, x, y - 2, z + 1) - u (t, x, y + 2,
							       z + 1)) +
				  3.33333333333333e-2 * (-u (t,
							      x,
							      y - 1,
							      z + 1) + u (t, x,
									  y + 1,
									  z +
									  1))) *
				 ti3 (x, y,
				      z + 1) + (-4.16666666666667e-2 * u (t,
									   x,
									   y,
									   z +
									   1) -
						1.25e-2 * u (t, x - 1, y,
							      z + 1) +
						7.5e-2 * u (t, x + 1, y,
							     z + 1) -
						2.5e-2 * u (t, x + 2, y,
							     z + 1) +
						4.16666666666667e-3 * u (t,
									  x + 3,
									  y,
									  z +
									  1))
				 * ti1 (x, y, z + 1)) * ti2 (x, y,
							     z + 1) -
				(3.33333333333333e-2 *
				 (-u (t, x, y, z) + u (t, x, y, z + 2)) +
				 4.16666666666667e-3 * (u (t, x, y, z - 1) -
							 u (t, x, y,
							    z + 3))) * ti0 (x,
									    y,
									    z
									    +
									    1))
			       * ti0 (x, y,
				      z + 1) +
			       1.25e-2 *
			       (((4.16666666666667e-3 *
				  (u (t, x - 2, y, z - 2) - u (t, x + 2, y,
							       z - 2)) +
				  3.33333333333333e-2 * (-u (t,
							      x - 1,
							      y,
							      z - 2) + u (t,
									  x + 1,
									  y,
									  z -
									  2))) *
				 ti1 (x, y,
				      z - 2) + (-4.16666666666667e-2 * u (t,
									   x,
									   y,
									   z -
									   2) -
						1.25e-2 * u (t, x, y - 1,
							      z - 2) +
						7.5e-2 * u (t, x, y + 1,
							     z - 2) -
						2.5e-2 * u (t, x, y + 2,
							     z - 2) +
						4.16666666666667e-3 * u (t,
									  x,
									  y + 3,
									  z -
									  2))
				 * ti3 (x, y, z - 2)) * ti2 (x, y,
							     z - 2) -
				(-2.5e-2 * u (t, x, y, z) -
				 1.25e-2 * u (t, x, y,
					       z - 3) -
				 4.16666666666667e-2 * u (t, x, y,
							   z - 2) +
				 7.5e-2 * u (t, x, y,
					      z - 1) +
				 4.16666666666667e-3 * u (t, x, y,
							   z + 1)) * ti0 (x, y,
									  z -
									  2)) *
			       ti0 (x, y,
				    z - 2) +
			       6.25e-3 *
			       (((4.16666666666667e-3 *
				  (u (t, x - 2, y, z + 1) - u (t, x + 2, y,
							       z + 1)) +
				  3.33333333333333e-2 * (-u (t,
							      x - 1,
							      y,
							      z + 1) + u (t,
									  x + 1,
									  y,
									  z +
									  1))) *
				 ti1 (x, y,
				      z + 1) + (-4.16666666666667e-2 * u (t,
									   x,
									   y,
									   z +
									   1) -
						1.25e-2 * u (t, x, y - 1,
							      z + 1) +
						7.5e-2 * u (t, x, y + 1,
							     z + 1) -
						2.5e-2 * u (t, x, y + 2,
							     z + 1) +
						4.16666666666667e-3 * u (t,
									  x,
									  y + 3,
									  z +
									  1))
				 * ti3 (x, y, z + 1)) * ti2 (x, y,
							     z + 1) -
				(-1.25e-2 * u (t, x, y, z) -
				 4.16666666666667e-2 * u (t, x, y,
							   z + 1) +
				 7.5e-2 * u (t, x, y, z + 2) - 2.5e-2 * u (t,
									     x,
									     y,
									     z +
									     3)
				 + 4.16666666666667e-3 * u (t, x, y,
							     z + 4)) * ti0 (x,
									    y,
									    z +
									    1))
			       * ti0 (x, y, z + 1));
    yc_number_node_ptr temp290 =
      (((4.16666666666667e-3 * (-v (t, x, y, z) + v (t, x - 4, y, z)) +
	 3.33333333333333e-2 * (-v (t, x - 3, y, z) +
				 v (t, x - 1, y, z))) * ti1 (x - 2, y,
							     z) +
	(-4.16666666666667e-2 * v (t, x - 2, y, z) -
	 1.25e-2 * v (t, x - 2, y - 1, z) + 7.5e-2 * v (t, x - 2, y + 1,
							  z) - 2.5e-2 * v (t,
									    x -
									    2,
									    y +
									    2,
									    z) +
	 4.16666666666667e-3 * v (t, x - 2, y + 3, z)) * ti3 (x - 2, y,
							       z)) * ti0 (x - 2,
									  y,
									  z) +
       (-4.16666666666667e-2 * v (t, x - 2, y,
				   z) - 1.25e-2 * v (t, x - 2, y,
						      z - 1) +
	7.5e-2 * v (t, x - 2, y, z + 1) - 2.5e-2 * v (t, x - 2, y,
							z + 2) +
	4.16666666666667e-3 * v (t, x - 2, y, z + 3)) * ti2 (x - 2,
							      y,
							      z)) * ti0 (x - 2,
									 y,
									 z) *
      ti1 (x - 2, y, z);
    yc_number_node_ptr temp275 =
      (((3.33333333333333e-2 * (v (t, x, y, z) - v (t, x, y - 2, z)) +
	 4.16666666666667e-3 * (v (t, x, y - 3, z) -
				 v (t, x, y + 1, z))) * ti3 (x, y - 1,
							     z) +
	(-4.16666666666667e-2 * v (t, x, y - 1, z) -
	 1.25e-2 * v (t, x - 1, y - 1, z) + 7.5e-2 * v (t, x + 1, y - 1,
							  z) - 2.5e-2 * v (t,
									    x +
									    2,
									    y -
									    1,
									    z) +
	 4.16666666666667e-3 * v (t, x + 3, y - 1, z)) * ti1 (x, y - 1,
							       z)) * ti0 (x,
									  y - 1,
									  z)
       +
       (4.16666666666667e-3 *
	(v (t, x, y - 1, z - 2) - v (t, x, y - 1, z + 2)) +
	3.33333333333333e-2 * (-v (t, x, y - 1, z - 1) +
				v (t, x, y - 1, z + 1))) * ti2 (x, y - 1,
								z)) * ti0 (x,
									   y -
									   1,
									   z) *
      ti3 (x, y - 1, z);
    yc_number_node_ptr temp237 =
      (((3.33333333333333e-2 * (-v (t, x, y, z) + v (t, x, y + 2, z)) +
	 4.16666666666667e-3 * (v (t, x, y - 1, z) -
				 v (t, x, y + 3, z))) * ti3 (x, y + 1,
							     z) +
	(-4.16666666666667e-2 * v (t, x, y + 1, z) -
	 1.25e-2 * v (t, x - 1, y + 1, z) + 7.5e-2 * v (t, x + 1, y + 1,
							  z) - 2.5e-2 * v (t,
									    x +
									    2,
									    y +
									    1,
									    z) +
	 4.16666666666667e-3 * v (t, x + 3, y + 1, z)) * ti1 (x, y + 1,
							       z)) * ti0 (x,
									  y + 1,
									  z)
       +
       (4.16666666666667e-3 *
	(v (t, x, y + 1, z - 2) - v (t, x, y + 1, z + 2)) +
	3.33333333333333e-2 * (-v (t, x, y + 1, z - 1) +
				v (t, x, y + 1, z + 1))) * ti2 (x, y + 1,
								z)) * ti0 (x,
									   y +
									   1,
									   z) *
      ti3 (x, y + 1, z);
    yc_number_node_ptr temp262 =
      (((4.16666666666667e-3 * (v (t, x, y, z) - v (t, x, y + 4, z)) +
	 3.33333333333333e-2 * (-v (t, x, y + 1, z) +
				 v (t, x, y + 3, z))) * ti3 (x, y + 2,
							     z) +
	(-4.16666666666667e-2 * v (t, x, y + 2, z) -
	 1.25e-2 * v (t, x - 1, y + 2, z) + 7.5e-2 * v (t, x + 1, y + 2,
							  z) - 2.5e-2 * v (t,
									    x +
									    2,
									    y +
									    2,
									    z) +
	 4.16666666666667e-3 * v (t, x + 3, y + 2, z)) * ti1 (x, y + 2,
							       z)) * ti0 (x,
									  y + 2,
									  z)
       +
       (4.16666666666667e-3 *
	(v (t, x, y + 2, z - 2) - v (t, x, y + 2, z + 2)) +
	3.33333333333333e-2 * (-v (t, x, y + 2, z - 1) +
				v (t, x, y + 2, z + 1))) * ti2 (x, y + 2,
								z)) * ti0 (x,
									   y +
									   2,
									   z) *
      ti3 (x, y + 2, z);
    yc_number_node_ptr temp68 =
      ((4.16666666666667e-3 * (v (t, x - 2, y, z) - v (t, x + 2, y, z)) +
	3.33333333333333e-2 * (-v (t, x - 1, y, z) +
				v (t, x + 1, y, z))) * ti1 (x, y,
							    z) +
       (-4.16666666666667e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x, y - 1, z) +
	7.5e-2 * v (t, x, y + 1,
		     z) - 2.5e-2 * v (t, x,
				       y + 2,
				       z) +
	4.16666666666667e-3 * v (t, x, y + 3, z)) * ti3 (x, y, z)) * ti0 (x,
									   y,
									   z)
      + (-4.16666666666667e-2 * v (t, x, y, z) -
	 1.25e-2 * v (t, x, y, z - 1) + 7.5e-2 * v (t, x, y,
						      z + 1) - 2.5e-2 * v (t,
									    x,
									    y,
									    z
									    +
									    2)
	 + 4.16666666666667e-3 * v (t, x, y, z + 3)) * ti2 (x, y, z);
    yc_number_node_ptr temp6 =
      1.0 / (8.85879567828298e-1 * damp (x, y, z) + 2.0 * m (x, y, z));
    yc_number_node_ptr temp225 =
      (((4.16666666666667e-3 *
	 (v (t, x + 1, y - 2, z) - v (t, x + 1, y + 2, z)) +
	 3.33333333333333e-2 * (-v (t, x + 1, y - 1, z) +
				 v (t, x + 1, y + 1, z))) * ti3 (x + 1, y,
								 z) +
	(-1.25e-2 * v (t, x, y, z) -
	 4.16666666666667e-2 * v (t, x + 1, y, z) + 7.5e-2 * v (t, x + 2, y,
								  z) -
	 2.5e-2 * v (t, x + 3, y, z) + 4.16666666666667e-3 * v (t, x + 4, y,
								  z)) * ti1 (x +
									     1,
									     y,
									     z))
       * ti0 (x + 1, y,
	      z) +
       (4.16666666666667e-3 *
	(v (t, x + 1, y, z - 2) - v (t, x + 1, y, z + 2)) +
	3.33333333333333e-2 * (-v (t, x + 1, y, z - 1) +
				v (t, x + 1, y, z + 1))) * ti2 (x + 1, y,
								z)) * ti0 (x +
									   1,
									   y,
									   z)
      * ti1 (x + 1, y, z);

    // Next time-step values.
    u (t + 1, x, y,
       z) EQUALS temp6 *(temp10 * u (t - 1, x, y,
				     z) +
			 1.5695652173913 * (temp487 * epsilon (x, y, z) +
					     (2.08333333333333e-2 *
					      (temp56 +
					       temp68 * (ti0 (x, y, z) *
							 ti3 (x, y,
							      z) + ti2 (x, y,
									z))) +
					      1.25e-2 * (temp185 + temp284 +
							  temp308) -
					      3.75e-2 * (temp204 + temp286 +
							  temp309) +
					      6.25e-3 * (temp225 + temp288 +
							  temp310) +
					      1.66666666666667e-2 *
					      (-temp154 + temp237 - temp275 +
					       temp289 - temp299 + temp92) +
					      2.08333333333333e-3 *
					      (temp116 - temp133 - temp165 +
					       temp252 - temp262 - temp283 +
					       temp290 - temp298 -
					       temp307)) * delta (x, y,
								  z)) +
			 4.0 * m (x, y, z) * u (t, x, y, z));
    v (t + 1, x, y,
       z) EQUALS temp6 *(temp10 * v (t - 1, x, y,
				     z) + 1.5695652173913 * temp487 * delta (x,
									      y,
									      z)
			 + 3.26992753623188e-2 * (temp56 +
						   temp68 * (ti0 (x, y, z) *
							     ti3 (x, y,
								  z) + ti2 (x,
									    y,
									    z)))
			 + 1.96195652173913e-2 * (temp185 + temp284 +
						   temp308) -
			 5.88586956521739e-2 * (temp204 + temp286 + temp309) +
			 9.80978260869565e-3 * (temp225 + temp288 + temp310) +
			 2.61594202898551e-2 * (-temp154 + temp237 - temp275 +
						 temp289 - temp299 + temp92) +
			 3.26992753623188e-3 * (temp116 - temp133 - temp165 +
						 temp252 - temp262 - temp283 +
						 temp290 - temp298 - temp307) +
			 4.0 * m (x, y, z) * v (t, x, y, z));

  }

  // Required stencil-definition method.
  virtual void define ()
  {
    switch (_radius)
      {
      case 2:
	define_so4 ();
	break;
      case 4:
	define_so8 ();
	break;
      default: {
          yask_exception e("Error: only radius values of 2 and 4 are currently supported for the TTI stencil example");
          throw e;
      }
      }
  }
};

// Create an object of type 'TTIStencil',
// making it available in the YASK compiler utility via the
// '-stencil' commmand-line option or the 'stencil=' build option.
static TTIStencil TTIStencil_instance;
