/*****************************************************************************

YASK: Yet Another Stencil Kit
Copyright (c) 2014-2022, Intel Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

* The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.

*****************************************************************************/

// Implement TTI stencil using formulation from Devito project.

// YASK stencil solution(s) in this file will be integrated into the YASK compiler utility.
#include "yask_compiler_api.hpp"
using namespace std;
using namespace yask;

// Create an anonymous namespace to ensure that types are local.
namespace
{

  class TTIStencil:public yc_solution_with_radius_base
  {

  protected:

    // Indices & dimensions.
    yc_index_node_ptr t = new_step_index ("t");	// step in time dim.
    yc_index_node_ptr x = new_domain_index ("x");	// spatial dim.
    yc_index_node_ptr y = new_domain_index ("y");	// spatial dim.
    yc_index_node_ptr z = new_domain_index ("z");	// spatial dim.

    // Vars.
    yc_var_proxy u = yc_var_proxy ("u", get_soln (), { t, x, y, z }
    );				// Time-varying 3D wavefield var.
    yc_var_proxy v = yc_var_proxy ("v", get_soln (), { t, x, y, z }
    );				// Time-varying 3D wavefield var.
    yc_var_proxy m = yc_var_proxy ("m", get_soln (), { x, y, z }
    );				// Square slowness of the model.
    yc_var_proxy damp = yc_var_proxy ("damp", get_soln (), { x, y, z }
    );				// Boundary damping.
    yc_var_proxy phi = yc_var_proxy ("phi", get_soln (), { x, y, z }
    );
    yc_var_proxy theta = yc_var_proxy ("theta", get_soln (), { x, y, z }
    );
    yc_var_proxy delta = yc_var_proxy ("delta", get_soln (), { x, y, z }
    );
    yc_var_proxy epsilon = yc_var_proxy ("epsilon", get_soln (), { x, y, z }
    );

    // Hoisted misc time-invariant data.
    yc_var_proxy ti0 = yc_var_proxy ("ti0", get_soln (), { x, y, z }
    );
    yc_var_proxy ti1 = yc_var_proxy ("ti1", get_soln (), { x, y, z }
    );
    yc_var_proxy ti2 = yc_var_proxy ("ti2", get_soln (), { x, y, z }
    );
    yc_var_proxy ti3 = yc_var_proxy ("ti3", get_soln (), { x, y, z }
    );

  public:

    // For this stencil, the 'radius' is the number of FD coefficients on
    // either side of center in each spatial dimension.
  TTIStencil (int radius = 2):
    yc_solution_with_radius_base ("tti", radius)
    {
    }

    // Define equation for 'u' and 'v' at t+1 based on values at t
    // for spatial order = 4.
    virtual void define_so4 ()
    {
      // Set BKC (best-known configs) found by automated and/or manual
      // tuning. 
      // Only have BKCs for SP FP (4B).
      auto soln = get_soln ();	// pointer to compile-time soln.
      if (soln->get_element_bytes () == 4)
	{

	  // Kernel run-time defaults, e.g., block-sizes.
	  // This code is run immediately after 'kernel_soln' is created.
	  soln->CALL_AFTER_NEW_SOLUTION
	    (kernel_soln.set_block_size ("x", 80);
	    kernel_soln.set_block_size ("y", 16);
	    kernel_soln.set_block_size ("z", 40););
	}

      // The following statements were auto-generated by the Devito symbolic
      // finite-difference package.

      auto temp161 = 2.5e-2 * (-u (t, x - 1, y, z) + u (t, x + 1, y, z));
      auto temp163 = -7.5e-2 * u (t, x, y, z) + 1.0e-1 * u (t, x, y + 1,
	z) - 2.5e-2 * u (t, x, y + 2,
	z);
      auto temp192 = 1.0e-1 * u (t, x, y, z) - 7.5e-2 * u (t, x, y - 1,
	z) - 2.5e-2 * u (t, x, y + 1,
	z);
      auto temp183 = -2.5e-2 * u (t, x, y, z) - 7.5e-2 * u (t, x - 2, y,
	z) + 1.0e-1 * u (t, x - 1, y,
	z);
      auto temp168 =
	-7.5e-2 * u (t, x, y + 1, z) + 1.0e-1 * u (t, x + 1, y + 1,
	z) - 2.5e-2 * u (t, x + 2,
	y + 1,
	z);
      auto temp197 =
	3.75e-2 * (temp161 * ti1 (x, y, z) * ti2 (x, y, z) + temp163 * ti2 (x,
	  y, z) * ti3 (x, y,
	  z) - (-7.5e-2 * u (t, x, y,
	    z) + 1.0e-1 * u (t, x, y,
	    z + 1) - 2.5e-2 * u (t, x, y,
	    z + 2)) * ti0 (x, y, z));
      auto temp171 =
	-7.5e-2 * u (t, x + 1, y, z) + 1.0e-1 * u (t, x + 1, y + 1,
	z) - 2.5e-2 * u (t, x + 1,
	y + 2,
	z);
      auto temp178 = 2.5e-2 * (u (t, x, y, z) - u (t, x - 2, y, z));
      auto temp182 =
	2.5e-2 * (-u (t, x - 2, y - 1, z) + u (t, x - 2, y + 1, z));
      auto temp190 = 1.0e-1 * u (t, x, y, z) - 7.5e-2 * u (t, x - 1, y,
	z) - 2.5e-2 * u (t, x + 1, y,
	z);
      auto temp173 = 2.5e-2 * (u (t, x, y, z) - u (t, x, y - 2, z));
      auto temp188 =
	2.5e-2 * (-u (t, x - 1, y - 1, z) + u (t, x - 1, y + 1, z));
      auto temp154 = 2.5e-2 * (-u (t, x, y - 1, z) + u (t, x, y + 1, z));
      auto temp186 = -2.5e-2 * u (t, x, y, z) - 7.5e-2 * u (t, x, y - 2,
	z) + 1.0e-1 * u (t, x, y - 1,
	z);
      auto temp158 = -7.5e-2 * u (t, x, y, z) + 1.0e-1 * u (t, x + 1, y,
	z) - 2.5e-2 * u (t, x + 2, y,
	z);
      auto temp191 =
	2.5e-2 * (-u (t, x - 1, y - 1, z) + u (t, x + 1, y - 1, z));
      auto temp184 =
	2.5e-2 * (-u (t, x - 1, y - 2, z) + u (t, x + 1, y - 2, z));
      auto temp181 =
	-7.5e-2 * u (t, x - 1, y, z) + 1.0e-1 * u (t, x - 1, y + 1,
	z) - 2.5e-2 * u (t, x - 1,
	y + 2,
	z);
      auto temp176 =
	-7.5e-2 * u (t, x, y - 1, z) + 1.0e-1 * u (t, x + 1, y - 1,
	z) - 2.5e-2 * u (t, x + 2,
	y - 1,
	z);
      auto temp123 =
	(2.5e-2 * ((v (t, x, y, z) - v (t, x, y - 2, z)) * ti0 (x, y - 1,
	    z) * ti3 (x,
	    y - 1,
	    z) + (-v (t, x, y - 1, z - 1) + v (t, x, y - 1, z + 1)) * ti2 (x,
	    y - 1,
	    z)) + (-7.5e-2 * v (t, x, y - 1, z) + 1.0e-1 * v (t, x + 1, y - 1,
	    z) - 2.5e-2 * v (t, x + 2, y - 1, z)) * ti0 (x, y - 1,
	  z) * ti1 (x, y - 1,
	  z)) * ti0 (x, y - 1, z) * ti3 (x, y - 1, z);
      auto temp102 =
	(2.5e-2 * ((-v (t, x - 1, y, z - 1) + v (t, x - 1, y,
	      z + 1)) * ti2 (x - 1, y,
	    z) + (-v (t,
	      x - 1,
	      y - 1,
	      z) + v (t,
	      x - 1,
	      y + 1,
	      z)) * ti0 (x - 1, y, z) * ti3 (x - 1, y, z)) + (1.0e-1 * v (t,
	    x, y,
	    z) - 7.5e-2 * v (t, x - 1, y,
	    z) - 2.5e-2 * v (t, x + 1, y,
	    z)) * ti0 (x - 1,
	  y,
	  z) * ti1 (x - 1, y, z)) * ti0 (x - 1, y,
	z) * ti1 (x - 1, y, z);
      auto temp131 =
	(2.5e-2 * (-v (t, x - 1, y, z - 2) + v (t, x + 1, y, z - 2)) * ti0 (x,
	  y, z - 2) * ti1 (x, y,
	  z - 2) + (-2.5e-2 * v (t, x, y,
	    z) - 7.5e-2 * v (t,
	    x,
	    y,
	    z - 2) + 1.0e-1 * v (t, x, y,
	    z - 1)) * ti2 (x, y,
	  z - 2) +
	(-7.5e-2 * v (t, x, y, z - 2) + 1.0e-1 * v (t, x, y + 1,
	    z - 2) - 2.5e-2 * v (t, x, y + 2, z - 2)) * ti0 (x, y,
	  z - 2) * ti3 (x, y,
	  z - 2)) * ti2 (x, y, z - 2);
      auto temp87 =
	(2.5e-2 * ((-v (t, x - 2, y, z - 1) + v (t, x - 2, y,
	      z + 1)) * ti2 (x - 2, y,
	    z) + (-v (t,
	      x - 2,
	      y - 1,
	      z) + v (t,
	      x - 2,
	      y + 1,
	      z)) * ti0 (x - 2, y, z) * ti3 (x - 2, y, z)) + (-2.5e-2 * v (t,
	    x, y,
	    z) - 7.5e-2 * v (t, x - 2, y,
	    z) + 1.0e-1 * v (t, x - 1, y,
	    z)) * ti0 (x - 2,
	  y,
	  z) * ti1 (x - 2, y, z)) * ti0 (x - 2, y,
	z) * ti1 (x - 2, y, z);
      auto temp47 =
	2.5e-2 * (-v (t, x - 1, y, z) + v (t, x + 1, y, z)) * ti0 (x, y,
	z) * ti1 (x,
	y,
	z) + (-7.5e-2 * v (t, x, y, z) + 1.0e-1 * v (t, x, y,
	  z + 1) - 2.5e-2 * v (t, x, y, z + 2)) * ti2 (x, y,
	z) + (-7.5e-2 * v (t, x,
	  y,
	  z) + 1.0e-1 * v (t, x,
	  y + 1,
	  z) - 2.5e-2 * v (t, x,
	  y + 2,
	  z)) * ti0 (x, y, z) * ti3 (x, y, z);
      auto temp110 =
	(2.5e-2 * ((-v (t, x, y, z) + v (t, x, y + 2, z)) * ti0 (x, y + 1,
	    z) * ti3 (x,
	    y + 1,
	    z) + (-v (t, x, y + 1, z - 1) + v (t, x, y + 1, z + 1)) * ti2 (x,
	    y + 1,
	    z)) + (-7.5e-2 * v (t, x, y + 1, z) + 1.0e-1 * v (t, x + 1, y + 1,
	    z) - 2.5e-2 * v (t, x + 2, y + 1, z)) * ti0 (x, y + 1,
	  z) * ti1 (x, y + 1,
	  z)) * ti0 (x, y + 1, z) * ti3 (x, y + 1, z);
      auto temp140 =
	(2.5e-2 * (-v (t, x, y, z) + v (t, x + 2, y, z)) * ti0 (x + 1, y,
	  z) * ti1 (x + 1, y,
	  z) + (-7.5e-2 * v (t, x + 1, y, z) + 1.0e-1 * v (t, x + 1, y,
	    z + 1) - 2.5e-2 * v (t, x + 1, y,
	    z + 2)) * ti2 (x + 1, y,
	  z) +
	(-7.5e-2 * v (t, x + 1, y, z) + 1.0e-1 * v (t, x + 1, y + 1,
	    z) - 2.5e-2 * v (t, x + 1, y + 2, z)) * ti0 (x + 1, y,
	  z) * ti3 (x + 1, y,
	  z)) * ti0 (x + 1, y,
	z) * ti1 (x + 1, y,
	z);
      auto temp149 =
	(2.5e-2 * (-v (t, x - 1, y - 2, z) + v (t, x + 1, y - 2, z)) * ti0 (x,
	  y - 2, z) * ti1 (x, y - 2,
	  z) + (-2.5e-2 * v (t, x, y,
	    z) - 7.5e-2 * v (t, x,
	    y - 2,
	    z) + 1.0e-1 * v (t, x, y - 1, z)) * ti0 (x,
	  y - 2,
	  z) * ti3 (x, y - 2,
	  z) + (-7.5e-2 * v (t, x, y - 2, z) + 1.0e-1 * v (t, x, y - 2,
	    z + 1) - 2.5e-2 * v (t, x, y - 2, z + 2)) * ti2 (x, y - 2,
	  z)) * ti0 (x,
	y - 2,
	z) * ti3 (x, y - 2, z);
      auto temp39 =
	(2.5e-2 * ((-v (t, x, y, z - 1) + v (t, x, y, z + 1)) * ti2 (x, y,
	    z) + (-v (t, x,
	      y - 1,
	      z) + v (t,
	      x,
	      y + 1,
	      z)) * ti0 (x, y, z) * ti3 (x, y, z)) + (-7.5e-2 * v (t, x, y,
	    z) + 1.0e-1 * v (t,
	    x + 1,
	    y,
	    z) - 2.5e-2 * v (t, x + 2,
	    y,
	    z)) * ti0 (x, y,
	  z) * ti1 (x, y, z)) * ti0 (x, y, z) * ti1 (x, y, z);
      auto temp132 =
	(2.5e-2 * (-v (t, x - 1, y, z - 1) + v (t, x + 1, y, z - 1)) * ti0 (x,
	  y, z - 1) * ti1 (x, y,
	  z - 1) + (1.0e-1 * v (t, x, y,
	    z) - 7.5e-2 * v (t, x,
	    y,
	    z - 1) - 2.5e-2 * v (t, x, y,
	    z + 1)) * ti2 (x, y,
	  z - 1) +
	(-7.5e-2 * v (t, x, y, z - 1) + 1.0e-1 * v (t, x, y + 1,
	    z - 1) - 2.5e-2 * v (t, x, y + 2, z - 1)) * ti0 (x, y,
	  z - 1) * ti3 (x, y,
	  z - 1)) * ti2 (x, y, z - 1);
      auto temp6 =
	1.0 / (8.85879567828298e-1 * damp (x, y, z) + 2.0 * m (x, y, z));
      auto temp141 =
	(2.5e-2 * (v (t, x, y, z) - v (t, x - 2, y, z)) * ti0 (x - 1, y,
	  z) * ti1 (x - 1, y,
	  z) + (-7.5e-2 * v (t, x - 1, y, z) + 1.0e-1 * v (t, x - 1, y,
	    z + 1) - 2.5e-2 * v (t, x - 1, y,
	    z + 2)) * ti2 (x - 1,
	  y,
	  z)
	+ (-7.5e-2 * v (t, x - 1, y, z) + 1.0e-1 * v (t, x - 1, y + 1,
	    z) - 2.5e-2 * v (t, x - 1, y + 2, z)) * ti0 (x - 1, y,
	  z) * ti3 (x - 1, y,
	  z)) * ti0 (x - 1, y,
	z) * ti1 (x - 1, y,
	z);
      auto temp10 = 8.85879567828298e-1 * damp (x, y, z) - 2.0 * m (x, y, z);
      auto temp215 =
	3.75e-2 * (-temp154 * ti1 (x, y, z) + temp158 * ti3 (x, y,
	  z)) * ti3 (x,
	y,
	z) + (temp197 * ti3 (x, y,
	  z) + (3.75e-2 * (temp154 * ti3 (x, y,
	      z) + temp158 * ti1 (x,
	      y,
	      z)) * ti2 (x, y,
	    z) - 9.375e-4 * (-u (t, x, y, z - 1) + u (t, x, y,
	      z + 1)) * ti0 (x,
	    y,
	    z)) * ti1 (x, y,
	  z)) * ti2 (x,
	y,
	z)
	+ (1.25e-2 * (temp182 * ti3 (x - 2, y, z) + temp183 * ti1 (x - 2, y,
	    z)) * ti2 (x - 2,
	  y,
	  z) - 3.125e-4 * (-u (t, x - 2, y, z - 1) + u (t, x - 2, y,
	    z + 1)) * ti0 (x - 2,
	  y,
	  z)) * ti1 (x - 2,
	y,
	z) * ti2 (x - 2, y,
	z) +
	5.0e-2 * ((temp191 * ti3 (x, y - 1, z) - temp192 * ti1 (x, y - 1,
	    z)) * ti1 (x, y - 1,
	  z) + (2.5e-2 * (-u (t, x - 1, y, z - 1) + u (t, x + 1, y,
	      z - 1)) * ti1 (x, y,
	    z - 1) * ti2 (x,
	    y,
	    z - 1) - (1.0e-1 * u (t, x, y, z) - 7.5e-2 * u (t, x, y,
	      z - 1) - 2.5e-2 * u (t, x,
	      y,
	      z + 1)) * ti0 (x, y,
	    z - 1) + (-7.5e-2 * u (t, x,
	      y,
	      z - 1) + 1.0e-1 * u (t, x,
	      y + 1,
	      z - 1) - 2.5e-2 * u (t, x,
	      y + 2,
	      z - 1)) * ti2 (x, y,
	    z - 1) * ti3 (x, y, z - 1)) * ti0 (x, y,
	  z - 1)) +
	(1.25e-2 * temp168 * ti1 (x, y + 1, z) * ti2 (x, y + 1,
	  z) + 3.125e-4 * ((-u (t, x, y, z) + u (t, x, y + 2, z)) * ti2 (x,
	    y + 1, z) * ti3 (x, y + 1,
	    z) - (-u (t, x, y + 1,
	      z - 1) + u (t, x,
	      y + 1,
	      z + 1)) * ti0 (x, y + 1, z))) * ti2 (x, y + 1, z) * ti3 (x,
	y + 1,
	z) + (1.25e-2 * (temp171 * ti2 (x + 1, y, z) * ti3 (x + 1, y,
	    z) - (-7.5e-2 * u (t, x + 1, y, z) + 1.0e-1 * u (t, x + 1, y,
	      z + 1) - 2.5e-2 * u (t, x + 1, y, z + 2)) * ti0 (x + 1, y,
	    z)) + 3.125e-4 * (-u (t, x,
	    y,
	    z) + u (t,
	    x + 2,
	    y,
	    z)) * ti1 (x + 1, y, z) * ti2 (x + 1, y,
	  z)) * ti1 (x + 1,
	y,
	z) * ti2 (x + 1, y,
	z) + 1.25e-2 * ((-temp171 * ti1 (x + 1, y, z) + 2.5e-2 * (-u (t, x, y,
	      z) + u (t, x + 2, y, z)) * ti3 (x + 1, y,
	    z)) * ti3 (x + 1,
	  y,
	  z) + (-temp173 * ti1 (x, y - 1, z) + temp176 * ti3 (x, y - 1,
	    z)) * ti1 (x,
	  y - 1,
	  z) + (-temp182 * ti1 (x - 2, y,
	    z) + temp183 * ti3 (x - 2, y,
	    z)) * ti3 (x - 2,
	  y,
	  z)
	+ ((temp184 * ti1 (x, y - 2, z) + temp186 * ti3 (x, y - 2,
	      z)) * ti2 (x,
	    y - 2,
	    z) - (-7.5e-2 * u (t,
	      x,
	      y - 2,
	      z) + 1.0e-1 * u (t,
	      x,
	      y - 2,
	      z + 1) - 2.5e-2 * u (t,
	      x,
	      y - 2,
	      z + 2)) * ti0 (x, y - 2, z)) * ti2 (x, y - 2, z) * ti3 (x,
	  y - 2,
	  z) + (2.5e-2 * (-(u (t, x, y, z) - u (t, x, y, z - 2)) * ti0 (x, y,
	      z - 1) + (-u (t, x, y - 1, z - 1) + u (t, x, y + 1,
		z - 1)) * ti2 (x, y,
	      z - 1) * ti3 (x, y, z - 1)) + (-7.5e-2 * u (t, x, y,
	      z - 1) + 1.0e-1 * u (t,
	      x + 1,
	      y,
	      z - 1) - 2.5e-2 * u (t, x + 2, y, z - 1)) * ti1 (x,
	    y,
	    z -
	    1) *
	  ti2 (x, y, z - 1)) * ti0 (x, y, z - 1)) - (temp197 * ti0 (x, y,
	  z) + 3.75e-2 * (temp161 * ti3 (x, y,
	    z) - temp163 * ti1 (x,
	    y,
	    z)) * ti1 (x, y,
	  z) + 1.25e-2 * (temp168 * ti3 (x, y + 1,
	    z) - 2.5e-2 * (-u (t, x, y,
	      z) + u (t,
	      x,
	      y + 2,
	      z)) * ti1 (x, y + 1,
	    z)) * ti1 (x, y + 1,
	  z) + 1.25e-2 * (temp178 * ti3 (x - 1, y,
	    z) - temp181 * ti1 (x - 1, y,
	    z)) * ti3 (x - 1, y,
	  z) + 1.25e-2 * (temp184 * ti3 (x, y - 2,
	    z) - temp186 * ti1 (x,
	    y - 2,
	    z)) * ti1 (x, y - 2,
	  z) + 5.0e-2 * (-temp188 * ti1 (x - 1, y,
	    z) + temp190 * ti3 (x - 1,
	    y,
	    z)) * ti3 (x - 1, y,
	  z) + (1.25e-2 * (temp173 * ti3 (x, y - 1,
	      z) + temp176 * ti1 (x, y - 1,
	      z)) * ti2 (x, y - 1,
	    z) - 3.125e-4 * (-u (t, x, y - 1, z - 1) + u (t, x, y - 1,
	      z + 1)) * ti0 (x,
	    y - 1,
	    z)) * ti2 (x, y - 1, z) * ti3 (x,
	  y - 1,
	  z) + 1.25e-2 * ((temp178 * ti1 (x - 1, y,
	      z) + temp181 * ti3 (x - 1, y,
	      z)) * ti2 (x - 1, y,
	    z) - (-7.5e-2 * u (t, x - 1, y,
	      z) + 1.0e-1 * u (t,
	      x - 1,
	      y,
	      z + 1) - 2.5e-2 * u (t, x - 1, y,
	      z + 2)) * ti0 (x - 1,
	    y,
	    z)) * ti1 (x - 1,
	  y,
	  z) * ti2 (x - 1, y,
	  z) + (5.0e-2 * (temp188 * ti3 (x - 1, y,
	      z) + temp190 * ti1 (x - 1, y,
	      z)) * ti2 (x - 1, y,
	    z) - 1.25e-3 * (-u (t, x - 1, y, z - 1) + u (t, x - 1, y,
	      z + 1)) * ti0 (x - 1,
	    y,
	    z)) * ti1 (x - 1, y,
	  z) * ti2 (x - 1, y,
	  z) + 5.0e-2 * ((temp191 * ti1 (x, y - 1,
	      z) + temp192 * ti3 (x, y - 1,
	      z)) * ti2 (x,
	    y - 1,
	    z) - (-7.5e-2 * u (t, x, y - 1,
	      z) + 1.0e-1 * u (t,
	      x,
	      y - 1,
	      z + 1) - 2.5e-2 * u (t, x, y - 1,
	      z + 2)) * ti0 (x,
	    y - 1,
	    z)) * ti2 (x, y - 1,
	  z) * ti3 (x, y - 1,
	  z) + 1.25e-2 * (2.5e-2 * (-(-u (t, x, y,
		z) + u (t,
		x,
		y,
		z + 2)) * ti0 (x, y,
	      z + 1) + (-u (t, x, y - 1,
		z + 1) + u (t,
		x,
		y + 1,
		z + 1)) * ti2 (x, y,
	      z + 1) * ti3 (x, y,
	      z + 1)) + (-7.5e-2 * u (t, x, y,
	      z + 1) + 1.0e-1 * u (t,
	      x + 1,
	      y,
	      z + 1) - 2.5e-2 * u (t,
	      x + 2,
	      y,
	      z + 1)) * ti1 (x, y,
	    z + 1) * ti2 (x, y,
	    z + 1)) * ti0 (x, y,
	  z + 1) + 1.25e-2 * (2.5e-2 * (-u (t, x - 1, y,
	      z - 2) + u (t, x + 1,
	      y,
	      z - 2)) * ti1 (x,
	    y,
	    z - 2) * ti2 (x, y,
	    z - 2) - (-2.5e-2 * u (t, x, y,
	      z) - 7.5e-2 * u (t,
	      x,
	      y,
	      z - 2) + 1.0e-1 * u (t,
	      x,
	      y,
	      z - 1)) * ti0 (x, y,
	    z - 2) + (-7.5e-2 * u (t,
	      x,
	      y,
	      z - 2) + 1.0e-1 * u (t,
	      x,
	      y + 1,
	      z - 2) - 2.5e-2 * u (t,
	      x,
	      y + 2,
	      z - 2)) * ti2 (x, y,
	    z - 2) * ti3 (x, y,
	    z - 2)) * ti0 (x, y, z - 2));
      auto temp77 =
	(2.5e-2 * ((v (t, x, y, z) - v (t, x, y, z - 2)) * ti2 (x, y,
	    z - 1) + (-v (t,
	      x,
	      y - 1,
	      z - 1) + v (t,
	      x,
	      y + 1,
	      z - 1)) * ti0 (x, y, z - 1) * ti3 (x, y,
	    z - 1)) + (-7.5e-2 * v (t,
	    x,
	    y,
	    z - 1) + 1.0e-1 * v (t,
	    x + 1, y,
	    z - 1) - 2.5e-2 * v (t,
	    x + 2,
	    y,
	    z - 1)) * ti0 (x,
	  y,
	  z - 1) * ti1 (x, y,
	  z - 1)) * ti2 (x,
	y,
	z - 1);
      auto temp61 =
	(2.5e-2 * ((-v (t, x, y, z) + v (t, x, y, z + 2)) * ti2 (x, y,
	    z + 1) + (-v (t,
	      x,
	      y - 1,
	      z + 1) + v (t,
	      x,
	      y + 1,
	      z + 1)) * ti0 (x, y, z + 1) * ti3 (x, y,
	    z + 1)) + (-7.5e-2 * v (t,
	    x,
	    y,
	    z + 1) + 1.0e-1 * v (t,
	    x + 1, y,
	    z + 1) - 2.5e-2 * v (t,
	    x + 2,
	    y,
	    z + 1)) * ti0 (x,
	  y,
	  z + 1) * ti1 (x, y,
	  z + 1)) * ti2 (x,
	y,
	z + 1);
      auto temp150 =
	(2.5e-2 * (-v (t, x - 1, y - 1, z) + v (t, x + 1, y - 1, z)) * ti0 (x,
	  y - 1, z) * ti1 (x, y - 1,
	  z) + (1.0e-1 * v (t, x, y,
	    z) - 7.5e-2 * v (t, x,
	    y - 1,
	    z) - 2.5e-2 * v (t, x, y + 1, z)) * ti0 (x,
	  y - 1,
	  z) * ti3 (x, y - 1,
	  z) + (-7.5e-2 * v (t, x, y - 1, z) + 1.0e-1 * v (t, x, y - 1,
	    z + 1) - 2.5e-2 * v (t, x, y - 1, z + 2)) * ti2 (x, y - 1,
	  z)) * ti0 (x,
	y - 1,
	z) * ti3 (x, y - 1, z);

      // Next time-step values.
      u (t + 1, x, y,
	z) EQUALS temp6 *(temp10 * u (t - 1, x, y,
	  z) +
	1.5695652173913 * (temp215 * epsilon (x, y, z) +
	  (3.75e-2 *
	    (temp39 +
	      temp47 * (ti0 (x, y, z) *
		ti3 (x, y,
		  z) + ti2 (x, y,
		  z))) -
	    5.0e-2 * (temp102 + temp132 + temp150) + 1.25e-2 * (temp110 -
	      temp123 + temp131 + temp140 - temp141 + temp149 + temp61 -
	      temp77 + temp87)) * delta (x, y, z)) + 4.0 * m (x, y, z) * u (t,
	  x, y, z));
      v (t + 1, x, y, z) EQUALS temp6 *(temp10 * v (t - 1, x, y,
	  z) + 1.5695652173913 * temp215 * delta (x, y,
	  z) + 5.88586956521739e-2 * (temp39 + temp47 * (ti0 (x, y,
	      z) * ti3 (x, y, z) + ti2 (x, y,
	      z))) - 7.84782608695652e-2 * (temp102 + temp132 + temp150) +
	1.96195652173913e-2 * (temp110 - temp123 + temp131 + temp140 -
	  temp141 + temp149 + temp61 - temp77 + temp87) + 4.0 * m (x, y,
	  z) * v (t, x, y, z));

    }

    // Define equation for 'u' and 'v' at t+1 based on values at t
    // for spatial order = 8.
    virtual void define_so8 ()
    {

      auto temp330 =
	4.16666666666667e-3 * (u (t, x - 2, y, z) - u (t, x + 2, y,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 1, y, z) + u (t, x + 1, y,
	  z));
      auto temp333 =
	-4.16666666666667e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 1,
	z) + 7.5e-2 * u (t, x, y + 1, z) - 2.5e-2 * u (t, x, y + 2,
	z) + 4.16666666666667e-3 * u (t, x, y + 3, z);
      auto temp336 =
	3.33333333333333e-2 * (-u (t, x, y, z) + u (t, x, y + 2,
	  z)) + 4.16666666666667e-3 * (u (t, x, y - 1, z) - u (t, x, y + 3,
	  z));
      auto temp395 =
	4.16666666666667e-3 * (u (t, x - 2, y - 2, z) - u (t, x + 2, y - 2,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 1,
	  y - 2,
	  z) + u (t,
	  x + 1,
	  y - 2,
	  z));
      auto temp365 =
	-4.16666666666667e-2 * u (t, x - 2, y, z) - 1.25e-2 * u (t, x - 2,
	y - 1,
	z) + 7.5e-2 * u (t, x - 2, y + 1, z) - 2.5e-2 * u (t, x - 2, y + 2,
	z) + 4.16666666666667e-3 * u (t, x - 2, y + 3, z);
      auto temp375 =
	-4.16666666666667e-2 * u (t, x + 2, y, z) - 1.25e-2 * u (t, x + 2,
	y - 1,
	z) + 7.5e-2 * u (t, x + 2, y + 1, z) - 2.5e-2 * u (t, x + 2, y + 2,
	z) + 4.16666666666667e-3 * u (t, x + 2, y + 3, z);
      auto temp394 = -2.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x - 3, y,
	z) - 4.16666666666667e-2 * u (t, x - 2, y, z) + 7.5e-2 * u (t, x - 1,
	y,
	z) + 4.16666666666667e-3 * u (t, x + 1, y, z);
      auto temp407 =
	4.16666666666667e-3 * (u (t, x - 1, y - 2, z) - u (t, x - 1, y + 2,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 1,
	  y - 1,
	  z) + u (t,
	  x - 1,
	  y + 1,
	  z));
      auto temp352 =
	4.16666666666667e-3 * (-u (t, x, y, z) + u (t, x, y - 4,
	  z)) + 3.33333333333333e-2 * (-u (t, x, y - 3, z) + u (t, x, y - 1,
	  z));
      auto temp347 =
	-4.16666666666667e-2 * u (t, x + 1, y, z) - 1.25e-2 * u (t, x + 1,
	y - 1,
	z) + 7.5e-2 * u (t, x + 1, y + 1, z) - 2.5e-2 * u (t, x + 1, y + 2,
	z) + 4.16666666666667e-3 * u (t, x + 1, y + 3, z);
      auto temp409 =
	4.16666666666667e-3 * (u (t, x + 1, y - 2, z) - u (t, x + 1, y + 2,
	  z)) + 3.33333333333333e-2 * (-u (t, x + 1,
	  y - 1,
	  z) + u (t,
	  x + 1,
	  y + 1,
	  z));
      auto temp318 =
	4.16666666666667e-3 * (u (t, x, y - 2, z) - u (t, x, y + 2,
	  z)) + 3.33333333333333e-2 * (-u (t, x, y - 1, z) + u (t, x, y + 1,
	  z));
      auto temp381 =
	-4.16666666666667e-2 * u (t, x, y - 1, z) - 1.25e-2 * u (t, x - 1,
	y - 1,
	z) + 7.5e-2 * u (t, x + 1, y - 1, z) - 2.5e-2 * u (t, x + 2, y - 1,
	z) + 4.16666666666667e-3 * u (t, x + 3, y - 1, z);
      auto temp408 = 7.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x - 2, y,
	z) - 4.16666666666667e-2 * u (t, x - 1, y, z) - 2.5e-2 * u (t, x + 1,
	y,
	z) + 4.16666666666667e-3 * u (t, x + 2, y, z);
      auto temp390 =
	4.16666666666667e-3 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 4,
	z) - 4.16666666666667e-2 * u (t, x, y - 3, z) + 7.5e-2 * u (t, x,
	y - 2,
	z) - 2.5e-2 * u (t, x, y - 1, z);
      auto temp360 =
	4.16666666666667e-3 * (-u (t, x, y, z) + u (t, x - 4, y,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 3, y, z) + u (t, x - 1, y,
	  z));
      auto temp370 =
	-4.16666666666667e-2 * u (t, x, y + 2, z) - 1.25e-2 * u (t, x - 1,
	y + 2,
	z) + 7.5e-2 * u (t, x + 1, y + 2, z) - 2.5e-2 * u (t, x + 2, y + 2,
	z) + 4.16666666666667e-3 * u (t, x + 3, y + 2, z);
      auto temp357 =
	-4.16666666666667e-2 * u (t, x, y - 2, z) - 1.25e-2 * u (t, x - 1,
	y - 2,
	z) + 7.5e-2 * u (t, x + 1, y - 2, z) - 2.5e-2 * u (t, x + 2, y - 2,
	z) + 4.16666666666667e-3 * u (t, x + 3, y - 2, z);
      auto temp385 =
	-4.16666666666667e-2 * u (t, x - 1, y, z) - 1.25e-2 * u (t, x - 1,
	y - 1,
	z) + 7.5e-2 * u (t, x - 1, y + 1, z) - 2.5e-2 * u (t, x - 1, y + 2,
	z) + 4.16666666666667e-3 * u (t, x - 1, y + 3, z);
      auto temp377 =
	3.33333333333333e-2 * (u (t, x, y, z) - u (t, x, y - 2,
	  z)) + 4.16666666666667e-3 * (u (t, x, y - 3, z) - u (t, x, y + 1,
	  z));
      auto temp343 =
	3.33333333333333e-2 * (-u (t, x, y, z) + u (t, x + 2, y,
	  z)) + 4.16666666666667e-3 * (u (t, x - 1, y, z) - u (t, x + 3, y,
	  z));
      auto temp388 =
	4.16666666666667e-3 * (u (t, x - 2, y - 3, z) - u (t, x + 2, y - 3,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 1,
	  y - 3,
	  z) + u (t,
	  x + 1,
	  y - 3,
	  z));
      auto temp406 =
	-1.25e-2 * u (t, x, y, z) - 4.16666666666667e-2 * u (t, x, y + 1,
	z) + 7.5e-2 * u (t, x, y + 2, z) - 2.5e-2 * u (t, x, y + 3,
	z) + 4.16666666666667e-3 * u (t, x, y + 4, z);
      auto temp404 =
	4.16666666666667e-3 * (u (t, x - 2, y + 1, z) - u (t, x + 2, y + 1,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 1,
	  y + 1,
	  z) + u (t,
	  x + 1,
	  y + 1,
	  z));
      auto temp342 =
	-4.16666666666667e-2 * u (t, x, y + 1, z) - 1.25e-2 * u (t, x - 1,
	y + 1,
	z) + 7.5e-2 * u (t, x + 1, y + 1, z) - 2.5e-2 * u (t, x + 2, y + 1,
	z) + 4.16666666666667e-3 * u (t, x + 3, y + 1, z);
      auto temp410 =
	-1.25e-2 * u (t, x, y, z) - 4.16666666666667e-2 * u (t, x + 1, y,
	z) + 7.5e-2 * u (t, x + 2, y, z) - 2.5e-2 * u (t, x + 3, y,
	z) + 4.16666666666667e-3 * u (t, x + 4, y, z);
      auto temp367 =
	4.16666666666667e-3 * (u (t, x, y, z) - u (t, x, y + 4,
	  z)) + 3.33333333333333e-2 * (-u (t, x, y + 1, z) + u (t, x, y + 3,
	  z));
      auto temp399 =
	4.16666666666667e-3 * (u (t, x - 2, y - 1, z) - u (t, x + 2, y - 1,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 1,
	  y - 1,
	  z) + u (t,
	  x + 1,
	  y - 1,
	  z));
      auto temp325 =
	-4.16666666666667e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x - 1, y,
	z) + 7.5e-2 * u (t, x + 1, y, z) - 2.5e-2 * u (t, x + 2, y,
	z) + 4.16666666666667e-3 * u (t, x + 3, y, z);
      auto temp386 =
	4.16666666666667e-3 * (u (t, x - 3, y - 2, z) - u (t, x - 3, y + 2,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 3,
	  y - 1,
	  z) + u (t,
	  x - 3,
	  y + 1,
	  z));
      auto temp396 = -2.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 3,
	z) - 4.16666666666667e-2 * u (t, x, y - 2, z) + 7.5e-2 * u (t, x,
	y - 1,
	z) + 4.16666666666667e-3 * u (t, x, y + 1, z);
      auto temp401 = 7.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y - 2,
	z) - 4.16666666666667e-2 * u (t, x, y - 1, z) - 2.5e-2 * u (t, x,
	y + 1,
	z) + 4.16666666666667e-3 * u (t, x, y + 2, z);
      auto temp372 =
	4.16666666666667e-3 * (u (t, x, y, z) - u (t, x + 4, y,
	  z)) + 3.33333333333333e-2 * (-u (t, x + 1, y, z) + u (t, x + 3, y,
	  z));
      auto temp420 =
	2.08333333333333e-2 * ((temp330 * ti1 (x, y, z) + temp333 * ti3 (x, y,
	    z)) * ti2 (x, y,
	  z) - (-4.16666666666667e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y,
	    z - 1) + 7.5e-2 * u (t, x, y,
	    z + 1) - 2.5e-2 * u (t,
	    x,
	    y,
	    z +
	    2) + 4.16666666666667e-3 * u (t, x, y, z + 3)) * ti0 (x, y, z));
      auto temp387 =
	4.16666666666667e-3 * u (t, x, y, z) - 1.25e-2 * u (t, x - 4, y,
	z) - 4.16666666666667e-2 * u (t, x - 3, y, z) + 7.5e-2 * u (t, x - 2,
	y,
	z) - 2.5e-2 * u (t, x - 1, y, z);
      auto temp383 =
	3.33333333333333e-2 * (u (t, x, y, z) - u (t, x - 2, y,
	  z)) + 4.16666666666667e-3 * (u (t, x - 3, y, z) - u (t, x + 1, y,
	  z));
      auto temp392 =
	4.16666666666667e-3 * (u (t, x - 2, y - 2, z) - u (t, x - 2, y + 2,
	  z)) + 3.33333333333333e-2 * (-u (t, x - 2,
	  y - 1,
	  z) + u (t,
	  x - 2,
	  y + 1,
	  z));
      auto temp284 =
	(((4.16666666666667e-3 * (v (t, x - 2, y, z - 2) - v (t, x + 2, y,
		z - 2)) + 3.33333333333333e-2 * (-v (t, x - 1, y,
		z - 2) + v (t, x + 1, y, z - 2))) * ti1 (x, y,
	    z - 2) + (-4.16666666666667e-2 * v (t, x, y,
	      z - 2) - 1.25e-2 * v (t, x, y - 1, z - 2) + 7.5e-2 * v (t, x,
	      y + 1,
	      z - 2) - 2.5e-2 * v (t, x, y + 2,
	      z - 2) + 4.16666666666667e-3 * v (t, x,
	      y + 3,
	      z - 2)) * ti3 (x, y, z - 2)) * ti0 (x, y,
	  z - 2) + (-2.5e-2 * v (t, x, y,
	    z) - 1.25e-2 * v (t, x, y,
	    z - 3) - 4.16666666666667e-2 * v (t,
	    x,
	    y,
	    z - 2) + 7.5e-2 * v (t, x,
	    y,
	    z - 1) + 4.16666666666667e-3 * v (t,
	    x,
	    y,
	    z + 1)) * ti2 (x, y, z - 2)) * ti2 (x, y, z - 2);
      auto temp308 =
	(((4.16666666666667e-3 * (v (t, x - 2, y - 2, z) - v (t, x + 2, y - 2,
		z)) + 3.33333333333333e-2 * (-v (t, x - 1, y - 2, z) + v (t,
		x + 1, y - 2, z))) * ti1 (x, y - 2,
	    z) + (-2.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x, y - 3,
	      z) - 4.16666666666667e-2 * v (t, x, y - 2, z) + 7.5e-2 * v (t,
	      x, y - 1,
	      z) + 4.16666666666667e-3 * v (t, x, y + 1, z)) * ti3 (x, y - 2,
	    z)) * ti0 (x,
	  y - 2,
	  z) + (-4.16666666666667e-2 * v (t, x, y - 2, z) -
	  1.25e-2 * v (t, x, y - 2,
	    z - 1) + 7.5e-2 * v (t, x, y - 2,
	    z + 1) - 2.5e-2 * v (t, x, y - 2,
	    z + 2) + 4.16666666666667e-3 * v (t,
	    x,
	    y - 2,
	    z
	    +
	    3)) * ti2 (x, y - 2, z)) * ti0 (x, y - 2, z) * ti3 (x, y - 2, z);
      auto temp92 =
	(((4.16666666666667e-3 * (v (t, x, y - 2, z + 1) - v (t, x, y + 2,
		z + 1)) + 3.33333333333333e-2 * (-v (t, x, y - 1,
		z + 1) + v (t, x, y + 1, z + 1))) * ti3 (x, y,
	    z + 1) + (-4.16666666666667e-2 * v (t, x, y,
	      z + 1) - 1.25e-2 * v (t, x - 1, y, z + 1) + 7.5e-2 * v (t,
	      x + 1, y,
	      z + 1) - 2.5e-2 * v (t, x + 2, y,
	      z + 1) + 4.16666666666667e-3 * v (t,
	      x + 3,
	      y,
	      z + 1)) * ti1 (x, y, z + 1)) * ti0 (x, y,
	  z + 1) +
	(3.33333333333333e-2 * (-v (t, x, y, z) + v (t, x, y,
	      z + 2)) + 4.16666666666667e-3 * (v (t, x, y, z - 1) - v (t, x,
	      y, z + 3))) * ti2 (x, y,
	  z + 1)) * ti2 (x,
	y,
	z + 1);
      auto temp185 =
	(((4.16666666666667e-3 * (v (t, x - 2, y - 2, z) - v (t, x - 2, y + 2,
		z)) + 3.33333333333333e-2 * (-v (t, x - 2, y - 1, z) + v (t,
		x - 2, y + 1, z))) * ti3 (x - 2, y,
	    z) + (-2.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x - 3, y,
	      z) - 4.16666666666667e-2 * v (t, x - 2, y, z) + 7.5e-2 * v (t,
	      x - 1, y,
	      z) + 4.16666666666667e-3 * v (t, x + 1, y, z)) * ti1 (x - 2, y,
	    z)) * ti0 (x - 2,
	  y,
	  z) +
	(4.16666666666667e-3 * (v (t, x - 2, y, z - 2) - v (t, x - 2, y,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x - 2, y, z - 1) + v (t,
	      x - 2, y, z + 1))) * ti2 (x - 2, y,
	  z)) * ti0 (x - 2,
	y,
	z) * ti1 (x - 2, y, z);
      auto temp283 =
	(((4.16666666666667e-3 * (v (t, x - 2, y, z - 3) - v (t, x + 2, y,
		z - 3)) + 3.33333333333333e-2 * (-v (t, x - 1, y,
		z - 3) + v (t, x + 1, y, z - 3))) * ti1 (x, y,
	    z - 3) + (-4.16666666666667e-2 * v (t, x, y,
	      z - 3) - 1.25e-2 * v (t, x, y - 1, z - 3) + 7.5e-2 * v (t, x,
	      y + 1,
	      z - 3) - 2.5e-2 * v (t, x, y + 2,
	      z - 3) + 4.16666666666667e-3 * v (t, x,
	      y + 3,
	      z -
	      3)) *
	  ti3 (x, y, z - 3)) * ti0 (x, y,
	  z - 3) + (4.16666666666667e-3 * v (t,
	    x,
	    y,
	    z) - 1.25e-2 * v (t, x, y,
	    z - 4) - 4.16666666666667e-2 * v (t,
	    x,
	    y,
	    z - 3) + 7.5e-2 * v (t, x, y,
	    z - 2) - 2.5e-2 * v (t, x, y,
	    z - 1)) * ti2 (x,
	  y,
	  z - 3)) * ti2 (x, y, z - 3);
      auto temp309 =
	(((4.16666666666667e-3 * (v (t, x - 2, y - 1, z) - v (t, x + 2, y - 1,
		z)) + 3.33333333333333e-2 * (-v (t, x - 1, y - 1, z) + v (t,
		x + 1, y - 1, z))) * ti1 (x, y - 1,
	    z) + (7.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x, y - 2,
	      z) - 4.16666666666667e-2 * v (t, x, y - 1, z) - 2.5e-2 * v (t,
	      x, y + 1,
	      z) + 4.16666666666667e-3 * v (t, x, y + 2, z)) * ti3 (x, y - 1,
	    z)) * ti0 (x,
	  y - 1,
	  z) + (-4.16666666666667e-2 * v (t, x, y - 1, z) -
	  1.25e-2 * v (t, x, y - 1, z - 1) + 7.5e-2 * v (t,
	    x,
	    y - 1,
	    z + 1) - 2.5e-2 * v (t, x, y - 1,
	    z + 2) + 4.16666666666667e-3 * v (t, x,
	    y - 1,
	    z +
	    3)) * ti2 (x, y - 1, z)) * ti0 (x, y - 1, z) * ti3 (x, y - 1, z);
      auto temp310 =
	(((4.16666666666667e-3 * (v (t, x - 2, y + 1, z) - v (t, x + 2, y + 1,
		z)) + 3.33333333333333e-2 * (-v (t, x - 1, y + 1, z) + v (t,
		x + 1, y + 1, z))) * ti1 (x, y + 1,
	    z) + (-1.25e-2 * v (t, x, y, z) - 4.16666666666667e-2 * v (t, x,
	      y + 1, z) + 7.5e-2 * v (t, x, y + 2,
	      z) - 2.5e-2 * v (t, x, y + 3, z) + 4.16666666666667e-3 * v (t,
	      x, y + 4,
	      z)) * ti3 (x,
	    y + 1,
	    z)) * ti0 (x, y + 1,
	  z) + (-4.16666666666667e-2 * v (t, x,
	    y + 1,
	    z) - 1.25e-2 * v (t, x, y + 1,
	    z - 1) + 7.5e-2 * v (t,
	    x,
	    y + 1,
	    z + 1) - 2.5e-2 * v (t, x, y + 1,
	    z + 2) + 4.16666666666667e-3 * v (t, x, y + 1,
	    z + 3)) * ti2 (x,
	  y + 1,
	  z)) * ti0 (x,
	y + 1,
	z) * ti3 (x, y + 1, z);
      auto temp307 =
	(((4.16666666666667e-3 * (v (t, x - 2, y - 3, z) - v (t, x + 2, y - 3,
		z)) + 3.33333333333333e-2 * (-v (t, x - 1, y - 3, z) + v (t,
		x + 1, y - 3, z))) * ti1 (x, y - 3,
	    z) + (4.16666666666667e-3 * v (t, x, y, z) - 1.25e-2 * v (t, x,
	      y - 4, z) - 4.16666666666667e-2 * v (t, x,
	      y - 3,
	      z) + 7.5e-2 * v (t, x, y - 2, z) - 2.5e-2 * v (t, x, y - 1,
	      z)) * ti3 (x, y - 3,
	    z)) * ti0 (x,
	  y - 3,
	  z) +
	(-4.16666666666667e-2 * v (t, x, y - 3, z) - 1.25e-2 * v (t, x, y - 3,
	    z - 1) + 7.5e-2 * v (t, x, y - 3,
	    z + 1) - 2.5e-2 * v (t, x, y - 3,
	    z + 2) + 4.16666666666667e-3 * v (t, x,
	    y - 3,
	    z + 3)) * ti2 (x, y - 3, z)) * ti0 (x, y - 3, z) * ti3 (x, y - 3,
	z);
      auto temp298 =
	(((4.16666666666667e-3 * (v (t, x, y, z) - v (t, x + 4, y,
		z)) + 3.33333333333333e-2 * (-v (t, x + 1, y, z) + v (t,
		x + 3, y, z))) * ti1 (x + 2, y,
	    z) + (-4.16666666666667e-2 * v (t, x + 2, y, z) - 1.25e-2 * v (t,
	      x + 2, y - 1, z) + 7.5e-2 * v (t, x + 2, y + 1,
	      z) - 2.5e-2 * v (t,
	      x + 2,
	      y + 2,
	      z) + 4.16666666666667e-3 * v (t, x + 2, y + 3, z)) * ti3 (x + 2,
	    y,
	    z)) * ti0 (x + 2,
	  y,
	  z) + (-4.16666666666667e-2 * v (t, x + 2, y,
	    z) - 1.25e-2 * v (t,
	    x + 2,
	    y,
	    z - 1) + 7.5e-2 * v (t, x + 2, y, z + 1) - 2.5e-2 * v (t,
	    x + 2,
	    y,
	    z + 2) + 4.16666666666667e-3 * v (t, x + 2, y,
	    z + 3)) * ti2 (x + 2,
	  y,
	  z)) * ti0 (x + 2,
	y,
	z) * ti1 (x + 2, y, z);
      auto temp165 =
	(((4.16666666666667e-3 * (v (t, x - 3, y - 2, z) - v (t, x - 3, y + 2,
		z)) + 3.33333333333333e-2 * (-v (t, x - 3, y - 1, z) + v (t,
		x - 3, y + 1, z))) * ti3 (x - 3, y,
	    z) + (4.16666666666667e-3 * v (t, x, y, z) - 1.25e-2 * v (t,
	      x - 4, y, z) - 4.16666666666667e-2 * v (t, x - 3,
	      y,
	      z) + 7.5e-2 * v (t, x - 2, y, z) - 2.5e-2 * v (t, x - 1, y,
	      z)) * ti1 (x - 3, y,
	    z)) * ti0 (x - 3,
	  y,
	  z)
	+ (4.16666666666667e-3 * (v (t, x - 3, y, z - 2) - v (t, x - 3, y,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x - 3, y, z - 1) + v (t,
	      x - 3, y, z + 1))) * ti2 (x - 3, y,
	  z)) * ti0 (x - 3,
	y,
	z) * ti1 (x - 3, y, z);
      auto temp154 =
	(((4.16666666666667e-3 * (v (t, x, y - 2, z - 1) - v (t, x, y + 2,
		z - 1)) + 3.33333333333333e-2 * (-v (t, x, y - 1,
		z - 1) + v (t, x, y + 1, z - 1))) * ti3 (x, y,
	    z - 1) + (-4.16666666666667e-2 * v (t, x, y,
	      z - 1) - 1.25e-2 * v (t, x - 1, y, z - 1) + 7.5e-2 * v (t,
	      x + 1, y,
	      z - 1) - 2.5e-2 * v (t, x + 2, y,
	      z - 1) + 4.16666666666667e-3 * v (t,
	      x + 3,
	      y,
	      z - 1)) * ti1 (x, y, z - 1)) * ti0 (x, y,
	  z - 1) +
	(3.33333333333333e-2 * (v (t, x, y, z) - v (t, x, y,
	      z - 2)) + 4.16666666666667e-3 * (v (t, x, y, z - 3) - v (t, x,
	      y, z + 1))) * ti2 (x, y,
	  z - 1)) * ti2 (x,
	y,
	z - 1);
      auto temp299 =
	(((3.33333333333333e-2 * (v (t, x, y, z) - v (t, x - 2, y,
		z)) + 4.16666666666667e-3 * (v (t, x - 3, y, z) - v (t, x + 1,
		y, z))) * ti1 (x - 1, y,
	    z) + (-4.16666666666667e-2 * v (t, x - 1, y, z) - 1.25e-2 * v (t,
	      x - 1, y - 1, z) + 7.5e-2 * v (t, x - 1, y + 1,
	      z) - 2.5e-2 * v (t,
	      x - 1,
	      y + 2,
	      z) + 4.16666666666667e-3 * v (t, x - 1, y + 3, z)) * ti3 (x - 1,
	    y,
	    z)) * ti0 (x - 1,
	  y,
	  z) + (-4.16666666666667e-2 * v (t, x - 1, y,
	    z) - 1.25e-2 * v (t,
	    x - 1,
	    y,
	    z - 1) + 7.5e-2 * v (t, x - 1, y, z + 1) - 2.5e-2 * v (t,
	    x - 1,
	    y,
	    z + 2) + 4.16666666666667e-3 * v (t, x - 1, y,
	    z + 3)) * ti2 (x - 1,
	  y,
	  z)) * ti0 (x - 1,
	y,
	z) * ti1 (x - 1, y, z);
      auto temp289 =
	(((3.33333333333333e-2 * (-v (t, x, y, z) + v (t, x + 2, y,
		z)) + 4.16666666666667e-3 * (v (t, x - 1, y, z) - v (t, x + 3,
		y, z))) * ti1 (x + 1, y,
	    z) + (-4.16666666666667e-2 * v (t, x + 1, y, z) - 1.25e-2 * v (t,
	      x + 1, y - 1, z) + 7.5e-2 * v (t, x + 1, y + 1,
	      z) - 2.5e-2 * v (t,
	      x + 1,
	      y + 2,
	      z) + 4.16666666666667e-3 * v (t, x + 1, y + 3, z)) * ti3 (x + 1,
	    y,
	    z)) * ti0 (x + 1,
	  y,
	  z) + (-4.16666666666667e-2 * v (t, x + 1, y,
	    z) - 1.25e-2 * v (t,
	    x + 1,
	    y,
	    z - 1) + 7.5e-2 * v (t, x + 1, y, z + 1) - 2.5e-2 * v (t,
	    x + 1,
	    y,
	    z + 2) + 4.16666666666667e-3 * v (t, x + 1, y,
	    z + 3)) * ti2 (x + 1,
	  y,
	  z)) * ti0 (x + 1,
	y,
	z) * ti1 (x + 1, y, z);
      auto temp116 =
	(((4.16666666666667e-3 * (v (t, x, y - 2, z - 2) - v (t, x, y + 2,
		z - 2)) + 3.33333333333333e-2 * (-v (t, x, y - 1,
		z - 2) + v (t, x, y + 1, z - 2))) * ti3 (x, y,
	    z - 2) + (-4.16666666666667e-2 * v (t, x, y,
	      z - 2) - 1.25e-2 * v (t, x - 1, y, z - 2) + 7.5e-2 * v (t,
	      x + 1, y,
	      z - 2) - 2.5e-2 * v (t, x + 2, y,
	      z - 2) + 4.16666666666667e-3 * v (t,
	      x + 3,
	      y,
	      z - 2)) * ti1 (x, y, z - 2)) * ti0 (x, y,
	  z - 2) +
	(4.16666666666667e-3 * (-v (t, x, y, z) + v (t, x, y,
	      z - 4)) + 3.33333333333333e-2 * (-v (t, x, y, z - 3) + v (t, x,
	      y, z - 1))) * ti2 (x, y,
	  z - 2)) * ti2 (x,
	y,
	z - 2);
      auto temp56 =
	(((4.16666666666667e-3 * (v (t, x, y - 2, z) - v (t, x, y + 2,
		z)) + 3.33333333333333e-2 * (-v (t, x, y - 1, z) + v (t, x,
		y + 1, z))) * ti3 (x, y,
	    z) + (-4.16666666666667e-2 * v (t, x, y, z) - 1.25e-2 * v (t,
	      x - 1, y, z) + 7.5e-2 * v (t, x + 1, y,
	      z) - 2.5e-2 * v (t,
	      x + 2,
	      y,
	      z) + 4.16666666666667e-3 * v (t, x + 3, y, z)) * ti1 (x, y,
	    z)) * ti0 (x,
	  y,
	  z)
	+ (4.16666666666667e-3 * (v (t, x, y, z - 2) - v (t, x, y,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x, y, z - 1) + v (t, x,
	      y, z + 1))) * ti2 (x, y,
	  z)) * ti0 (x, y,
	z) * ti1 (x, y, z);
      auto temp204 =
	(((4.16666666666667e-3 * (v (t, x - 1, y - 2, z) - v (t, x - 1, y + 2,
		z)) + 3.33333333333333e-2 * (-v (t, x - 1, y - 1, z) + v (t,
		x - 1, y + 1, z))) * ti3 (x - 1, y,
	    z) + (7.5e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x - 2, y,
	      z) - 4.16666666666667e-2 * v (t, x - 1, y, z) - 2.5e-2 * v (t,
	      x + 1, y,
	      z) + 4.16666666666667e-3 * v (t, x + 2, y, z)) * ti1 (x - 1, y,
	    z)) * ti0 (x - 1,
	  y,
	  z) +
	(4.16666666666667e-3 * (v (t, x - 1, y, z - 2) - v (t, x - 1, y,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x - 1, y, z - 1) + v (t,
	      x - 1, y, z + 1))) * ti2 (x - 1, y,
	  z)) * ti0 (x - 1,
	y,
	z) * ti1 (x - 1, y, z);
      auto temp288 =
	(((4.16666666666667e-3 * (v (t, x - 2, y, z + 1) - v (t, x + 2, y,
		z + 1)) + 3.33333333333333e-2 * (-v (t, x - 1, y,
		z + 1) + v (t, x + 1, y, z + 1))) * ti1 (x, y,
	    z + 1) + (-4.16666666666667e-2 * v (t, x, y,
	      z + 1) - 1.25e-2 * v (t, x, y - 1, z + 1) + 7.5e-2 * v (t, x,
	      y + 1,
	      z + 1) - 2.5e-2 * v (t, x, y + 2,
	      z + 1) + 4.16666666666667e-3 * v (t, x,
	      y + 3,
	      z +
	      1)) * ti3 (x, y, z + 1)) * ti0 (x, y, z + 1) + (-1.25e-2 * v (t,
	    x, y,
	    z) - 4.16666666666667e-2 * v (t,
	    x,
	    y,
	    z + 1) + 7.5e-2 * v (t, x, y,
	    z + 2) - 2.5e-2 * v (t, x, y,
	    z + 3) + 4.16666666666667e-3 * v (t,
	    x,
	    y,
	    z + 4)) * ti2 (x, y, z + 1)) * ti2 (x, y, z + 1);
      auto temp10 = 8.85879567828298e-1 * damp (x, y, z) - 2.0 * m (x, y, z);
      auto temp133 =
	(((4.16666666666667e-3 * (v (t, x, y - 2, z + 2) - v (t, x, y + 2,
		z + 2)) + 3.33333333333333e-2 * (-v (t, x, y - 1,
		z + 2) + v (t, x, y + 1, z + 2))) * ti3 (x, y,
	    z + 2) + (-4.16666666666667e-2 * v (t, x, y,
	      z + 2) - 1.25e-2 * v (t, x - 1, y, z + 2) + 7.5e-2 * v (t,
	      x + 1, y,
	      z + 2) - 2.5e-2 * v (t, x + 2, y,
	      z + 2) + 4.16666666666667e-3 * v (t,
	      x + 3,
	      y,
	      z + 2)) * ti1 (x, y, z + 2)) * ti0 (x, y,
	  z + 2) +
	(4.16666666666667e-3 * (v (t, x, y, z) - v (t, x, y,
	      z + 4)) + 3.33333333333333e-2 * (-v (t, x, y, z + 1) + v (t, x,
	      y, z + 3))) * ti2 (x, y,
	  z + 2)) * ti2 (x,
	y,
	z + 2);
      auto temp286 =
	(((4.16666666666667e-3 * (v (t, x - 2, y, z - 1) - v (t, x + 2, y,
		z - 1)) + 3.33333333333333e-2 * (-v (t, x - 1, y,
		z - 1) + v (t, x + 1, y, z - 1))) * ti1 (x, y,
	    z - 1) + (-4.16666666666667e-2 * v (t, x, y,
	      z - 1) - 1.25e-2 * v (t, x, y - 1, z - 1) + 7.5e-2 * v (t, x,
	      y + 1,
	      z - 1) - 2.5e-2 * v (t, x, y + 2,
	      z - 1) + 4.16666666666667e-3 * v (t, x,
	      y + 3,
	      z - 1)) * ti3 (x, y, z - 1)) * ti0 (x, y,
	  z - 1) + (7.5e-2 * v (t, x, y,
	    z) - 1.25e-2 * v (t, x, y,
	    z - 2) - 4.16666666666667e-2 * v (t,
	    x,
	    y,
	    z - 1) - 2.5e-2 * v (t, x,
	    y,
	    z + 1) + 4.16666666666667e-3 * v (t,
	    x,
	    y,
	    z + 2)) * ti2 (x, y, z - 1)) * ti2 (x, y, z - 1);
      auto temp252 =
	(((4.16666666666667e-3 * (-v (t, x, y, z) + v (t, x, y - 4,
		z)) + 3.33333333333333e-2 * (-v (t, x, y - 3, z) + v (t, x,
		y - 1, z))) * ti3 (x, y - 2,
	    z) + (-4.16666666666667e-2 * v (t, x, y - 2, z) - 1.25e-2 * v (t,
	      x - 1, y - 2, z) + 7.5e-2 * v (t, x + 1, y - 2,
	      z) - 2.5e-2 * v (t,
	      x + 2,
	      y - 2,
	      z) + 4.16666666666667e-3 * v (t, x + 3, y - 2, z)) * ti1 (x,
	    y - 2,
	    z)) * ti0 (x,
	  y - 2,
	  z)
	+ (4.16666666666667e-3 * (v (t, x, y - 2, z - 2) - v (t, x, y - 2,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x, y - 2, z - 1) + v (t,
	      x, y - 2, z + 1))) * ti2 (x, y - 2,
	  z)) * ti0 (x,
	y - 2,
	z) * ti3 (x, y - 2, z);
      auto temp487 = temp420 * ti2 (x, y, z) * ti3 (x, y,
	z) + 2.08333333333333e-2 * ((-temp318 * ti1 (x, y,
	    z) + temp325 * ti3 (x, y, z)) * ti3 (x, y,
	  z) + ((temp318 * ti3 (x, y, z) + temp325 * ti1 (x, y, z)) * ti2 (x,
	    y,
	    z) - (4.16666666666667e-3 * (u (t, x, y, z - 2) - u (t, x, y,
		z + 2)) + 3.33333333333333e-2 * (-u (t, x, y, z - 1) + u (t,
		x, y, z + 1))) * ti0 (x, y,
	    z)) * ti1 (x,
	  y,
	  z) * ti2 (x, y,
	  z)) + 3.75e-2 * ((temp399 * ti3 (x, y - 1, z) - temp401 * ti1 (x,
	    y - 1,
	    z)) * ti1 (x, y - 1,
	  z) + (((4.16666666666667e-3 * (u (t, x - 2, y, z - 1) - u (t, x + 2,
		  y,
		  z - 1)) + 3.33333333333333e-2 * (-u (t,
		  x - 1,
		  y,
		  z - 1) + u (t,
		  x + 1,
		  y,
		  z - 1))) * ti1 (x, y,
	      z - 1) + (-4.16666666666667e-2 * u (t,
		x,
		y,
		z - 1) - 1.25e-2 * u (t, x, y - 1,
		z - 1) + 7.5e-2 * u (t, x, y + 1,
		z - 1) - 2.5e-2 * u (t, x, y + 2,
		z - 1) + 4.16666666666667e-3 * u (t,
		x,
		y + 3,
		z - 1)) * ti3 (x, y,
	      z - 1)) * ti2 (x, y,
	    z - 1) - (7.5e-2 * u (t, x, y, z) - 1.25e-2 * u (t, x, y,
	      z - 2) - 4.16666666666667e-2 * u (t, x, y,
	      z - 1) - 2.5e-2 * u (t, x, y,
	      z + 1) + 4.16666666666667e-3 * u (t, x, y,
	      z + 2)) * ti0 (x, y,
	    z - 1)) * ti0 (x, y,
	  z - 1)) + 1.25e-2 * ((-temp392 * ti1 (x - 2,
	    y,
	    z) + temp394 * ti3 (x - 2, y,
	    z)) * ti3 (x - 2, y,
	  z) + ((temp392 * ti3 (x - 2, y,
	      z) + temp394 * ti1 (x - 2,
	      y,
	      z)) * ti2 (x - 2, y,
	    z) - (4.16666666666667e-3 * (u (t, x - 2, y,
		z - 2) - u (t,
		x - 2, y,
		z + 2)) + 3.33333333333333e-2 * (-u (t, x - 2, y,
		z - 1) + u (t,
		x - 2, y,
		z + 1))) * ti0 (x - 2, y,
	    z)) * ti1 (x - 2, y,
	  z) * ti2 (x - 2,
	  y,
	  z) + ((temp395 * ti1 (x, y - 2,
	      z) + temp396 * ti3 (x,
	      y - 2,
	      z)) * ti2 (x, y - 2,
	    z) - (-4.16666666666667e-2 * u (t, x, y - 2,
	      z) - 1.25e-2 * u (t, x,
	      y - 2,
	      z - 1) + 7.5e-2 * u (t, x,
	      y - 2,
	      z + 1) - 2.5e-2 * u (t, x,
	      y - 2,
	      z + 2) + 4.16666666666667e-3 * u (t, x, y - 2,
	      z + 3)) * ti0 (x,
	    y - 2,
	    z)) * ti2 (x, y - 2,
	  z) * ti3 (x,
	  y - 2,
	  z))
	+ 6.25e-3 * ((-temp409 * ti1 (x + 1, y, z) + temp410 * ti3 (x + 1, y,
	    z)) * ti3 (x + 1,
	  y,
	  z) + ((temp404 * ti1 (x, y + 1, z) + temp406 * ti3 (x, y + 1,
	      z)) * ti2 (x,
	    y + 1,
	    z)
	  - (-4.16666666666667e-2 * u (t, x, y + 1, z) - 1.25e-2 * u (t, x,
	      y + 1, z - 1) + 7.5e-2 * u (t, x,
	      y + 1,
	      z + 1) - 2.5e-2 * u (t, x, y + 1,
	      z + 2) + 4.16666666666667e-3 * u (t, x,
	      y + 1,
	      z +
	      3)) * ti0 (x, y + 1, z)) * ti2 (x, y + 1, z) * ti3 (x, y + 1,
	  z) + ((temp409 * ti3 (x + 1, y, z) + temp410 * ti1 (x + 1, y,
	      z)) * ti2 (x + 1,
	    y,
	    z)
	  -
	  (4.16666666666667e-3 *
	    (u (t, x + 1, y, z - 2) - u (t, x + 1, y, z + 2)) +
	    3.33333333333333e-2 * (-u (t, x + 1, y, z - 1) + u (t, x + 1, y,
		z + 1))) * ti0 (x + 1, y,
	    z)) * ti1 (x + 1,
	  y,
	  z) * ti2 (x + 1, y,
	  z)) +
	1.66666666666667e-2 * ((temp343 * ti3 (x + 1, y,
	    z) - temp347 * ti1 (x + 1, y, z)) * ti3 (x + 1,
	  y,
	  z) + (-temp377 * ti1 (x, y - 1, z) + temp381 * ti3 (x, y - 1,
	    z)) * ti1 (x,
	  y - 1,
	  z) + ((temp336 * ti3 (x, y + 1, z) + temp342 * ti1 (x, y + 1,
	      z)) * ti2 (x,
	    y + 1,
	    z) -
	  (4.16666666666667e-3 *
	    (u (t, x, y + 1, z - 2) - u (t, x, y + 1, z + 2)) +
	    3.33333333333333e-2 * (-u (t, x, y + 1, z - 1) +
	      u (t, x, y + 1, z + 1))) * ti0 (x, y + 1,
	    z)) * ti2 (x,
	  y + 1,
	  z) * ti3 (x, y + 1,
	  z) + ((temp343 * ti1 (x + 1, y, z) + temp347 * ti3 (x + 1, y,
	      z)) * ti2 (x + 1, y,
	    z) - (-4.16666666666667e-2 * u (t, x + 1, y, z) - 1.25e-2 * u (t,
	      x + 1, y, z - 1) + 7.5e-2 * u (t,
	      x + 1,
	      y,
	      z + 1) - 2.5e-2 * u (t, x + 1, y,
	      z + 2) + 4.16666666666667e-3 * u (t, x + 1,
	      y,
	      z + 3)) * ti0 (x + 1, y, z)) * ti1 (x + 1, y, z) * ti2 (x + 1,
	  y,
	  z) + (((4.16666666666667e-3 * (u (t, x, y - 2, z - 1) - u (t, x,
		  y + 2, z - 1)) + 3.33333333333333e-2 * (-u (t, x, y - 1,
		  z - 1) + u (t, x, y + 1, z - 1))) * ti3 (x, y,
	      z - 1) + (-4.16666666666667e-2 * u (t, x, y,
		z - 1) - 1.25e-2 * u (t, x - 1, y, z - 1) + 7.5e-2 * u (t,
		x + 1, y,
		z - 1) - 2.5e-2 * u (t, x + 2, y,
		z - 1) + 4.16666666666667e-3 * u (t,
		x + 3,
		y,
		z - 1)) * ti1 (x, y, z - 1)) * ti2 (x, y,
	    z - 1) - (3.33333333333333e-2 * (u (t, x, y, z) - u (t, x, y,
		z - 2)) + 4.16666666666667e-3 * (u (t, x, y,
		z - 3) - u (t, x, y,
		z + 1))) * ti0 (x, y,
	    z - 1)) * ti0 (x,
	  y,
	  z
	  -
	  1))
	+ 2.08333333333333e-3 * ((temp360 * ti3 (x - 2, y,
	    z) - temp365 * ti1 (x - 2, y, z)) * ti3 (x - 2,
	  y,
	  z) + (-temp367 * ti1 (x, y + 2, z) + temp370 * ti3 (x, y + 2,
	    z)) * ti1 (x,
	  y + 2,
	  z) + (temp388 * ti3 (x, y - 3, z) - temp390 * ti1 (x, y - 3,
	    z)) * ti1 (x,
	  y - 3,
	  z)
	+ ((temp352 * ti3 (x, y - 2, z) + temp357 * ti1 (x, y - 2,
	      z)) * ti2 (x,
	    y - 2,
	    z)
	  - (4.16666666666667e-3 * (u (t, x, y - 2, z - 2) - u (t, x, y - 2,
		z + 2)) + 3.33333333333333e-2 * (-u (t, x, y - 2,
		z - 1) + u (t, x, y - 2, z + 1))) * ti0 (x, y - 2,
	    z)) * ti2 (x,
	  y - 2,
	  z) * ti3 (x, y - 2,
	  z) +
	((temp360 * ti1 (x - 2, y, z) + temp365 * ti3 (x - 2, y,
	      z)) * ti2 (x - 2, y,
	    z) - (-4.16666666666667e-2 * u (t, x - 2, y, z) - 1.25e-2 * u (t,
	      x - 2, y, z - 1) + 7.5e-2 * u (t,
	      x - 2,
	      y,
	      z + 1) - 2.5e-2 * u (t, x - 2, y,
	      z + 2) + 4.16666666666667e-3 * u (t, x - 2,
	      y,
	      z + 3)) * ti0 (x - 2, y, z)) * ti1 (x - 2, y, z) * ti2 (x - 2,
	  y,
	  z) + (((4.16666666666667e-3 * (u (t, x, y - 2, z + 2) - u (t, x,
		  y + 2, z + 2)) + 3.33333333333333e-2 * (-u (t, x, y - 1,
		  z + 2) + u (t, x, y + 1, z + 2))) * ti3 (x, y,
	      z + 2) + (-4.16666666666667e-2 * u (t, x, y,
		z + 2) - 1.25e-2 * u (t, x - 1, y, z + 2) + 7.5e-2 * u (t,
		x + 1, y,
		z + 2) - 2.5e-2 * u (t, x + 2, y,
		z + 2) + 4.16666666666667e-3 * u (t,
		x + 3,
		y,
		z + 2)) * ti1 (x, y, z + 2)) * ti2 (x, y,
	    z +
	    2) -
	  (4.16666666666667e-3 * (u (t, x, y, z) - u (t, x, y,
		z + 4)) + 3.33333333333333e-2 * (-u (t, x, y, z + 1) + u (t,
		x, y, z + 3))) * ti0 (x, y,
	    z + 2)) * ti0 (x,
	  y,
	  z
	  +
	  2)
	+ (((4.16666666666667e-3 * (u (t, x - 2, y, z - 3) - u (t, x + 2, y,
		  z - 3)) + 3.33333333333333e-2 * (-u (t, x - 1, y,
		  z - 3) + u (t, x + 1, y, z - 3))) * ti1 (x, y,
	      z - 3) + (-4.16666666666667e-2 * u (t, x, y,
		z - 3) - 1.25e-2 * u (t, x, y - 1, z - 3) + 7.5e-2 * u (t, x,
		y + 1,
		z - 3) - 2.5e-2 * u (t, x, y + 2,
		z - 3) + 4.16666666666667e-3 * u (t, x,
		y + 3,
		z - 3)) * ti3 (x, y, z - 3)) * ti2 (x, y,
	    z - 3) - (4.16666666666667e-3 * u (t, x,
	      y,
	      z) - 1.25e-2 * u (t, x, y,
	      z - 4) - 4.16666666666667e-2 * u (t, x,
	      y,
	      z - 3) + 7.5e-2 * u (t, x, y,
	      z - 2) - 2.5e-2 * u (t, x, y,
	      z - 1)) * ti0 (x,
	    y,
	    z - 3)) * ti0 (x, y, z - 3)) - (temp420 * ti0 (x, y,
	  z) + 2.08333333333333e-2 * (temp330 * ti3 (x, y,
	    z) - temp333 * ti1 (x, y,
	    z)) * ti1 (x, y,
	  z) + 1.66666666666667e-2 * (-temp336 * ti1 (x, y + 1,
	    z) + temp342 * ti3 (x,
	    y + 1,
	    z)) * ti1 (x, y + 1,
	  z) + 2.08333333333333e-3 * (-temp352 * ti1 (x, y - 2,
	    z) + temp357 * ti3 (x,
	    y - 2,
	    z)) * ti1 (x, y - 2,
	  z) + 2.08333333333333e-3 * (temp372 * ti3 (x + 2, y,
	    z) - temp375 * ti1 (x + 2, y,
	    z)) * ti3 (x + 2, y,
	  z) + 1.66666666666667e-2 * (temp383 * ti3 (x - 1, y,
	    z) - temp385 * ti1 (x - 1, y,
	    z)) * ti3 (x - 1, y,
	  z) + 2.08333333333333e-3 * (-temp386 * ti1 (x - 3, y,
	    z) + temp387 * ti3 (x - 3, y,
	    z)) * ti3 (x - 3, y,
	  z) + 1.25e-2 * (temp395 * ti3 (x,
	    y - 2,
	    z) - temp396 * ti1 (x,
	    y - 2,
	    z)) * ti1 (x, y - 2,
	  z) + 6.25e-3 * (temp404 * ti3 (x,
	    y + 1,
	    z) - temp406 * ti1 (x,
	    y + 1,
	    z)) * ti1 (x, y + 1,
	  z) + 3.75e-2 * (-temp407 * ti1 (x - 1, y,
	    z) + temp408 * ti3 (x - 1, y,
	    z)) * ti3 (x - 1, y,
	  z) + 2.08333333333333e-3 * ((temp367 * ti3 (x, y + 2,
	      z) + temp370 * ti1 (x,
	      y + 2,
	      z)) * ti2 (x, y + 2,
	    z) - (4.16666666666667e-3 * (u (t, x, y + 2,
		z - 2) - u (t, x,
		y + 2,
		z + 2)) + 3.33333333333333e-2 * (-u (t, x,
		y + 2,
		z - 1) + u (t, x,
		y + 2,
		z + 1))) * ti0 (x, y + 2,
	    z)) * ti2 (x,
	  y + 2,
	  z) * ti3 (x,
	  y + 2,
	  z) + 2.08333333333333e-3 * ((temp372 * ti1 (x + 2, y,
	      z) + temp375 * ti3 (x + 2,
	      y,
	      z)) * ti2 (x + 2, y,
	    z) - (-4.16666666666667e-2 * u (t, x + 2, y,
	      z) - 1.25e-2 * u (t,
	      x + 2,
	      y,
	      z - 1) + 7.5e-2 * u (t,
	      x + 2,
	      y,
	      z + 1) - 2.5e-2 * u (t,
	      x + 2,
	      y,
	      z + 2) + 4.16666666666667e-3 * u (t, x + 2, y,
	      z + 3)) * ti0 (x + 2,
	    y,
	    z)) * ti1 (x + 2, y,
	  z) * ti2 (x + 2,
	  y,
	  z) + 1.66666666666667e-2 * ((temp377 * ti3 (x, y - 1,
	      z) + temp381 * ti1 (x,
	      y - 1,
	      z)) * ti2 (x, y - 1,
	    z) - (4.16666666666667e-3 * (u (t, x, y - 1,
		z - 2) - u (t, x,
		y - 1,
		z + 2)) + 3.33333333333333e-2 * (-u (t, x,
		y - 1,
		z - 1) + u (t, x,
		y - 1,
		z + 1))) * ti0 (x, y - 1,
	    z)) * ti2 (x,
	  y - 1,
	  z) * ti3 (x,
	  y - 1,
	  z) + 1.66666666666667e-2 * ((temp383 * ti1 (x - 1, y,
	      z) + temp385 * ti3 (x - 1,
	      y,
	      z)) * ti2 (x - 1, y,
	    z) - (-4.16666666666667e-2 * u (t, x - 1, y,
	      z) - 1.25e-2 * u (t,
	      x - 1,
	      y,
	      z - 1) + 7.5e-2 * u (t,
	      x - 1,
	      y,
	      z + 1) - 2.5e-2 * u (t,
	      x - 1,
	      y,
	      z + 2) + 4.16666666666667e-3 * u (t, x - 1, y,
	      z + 3)) * ti0 (x - 1,
	    y,
	    z)) * ti1 (x - 1, y,
	  z) * ti2 (x - 1,
	  y,
	  z) + 2.08333333333333e-3 * ((temp386 * ti3 (x - 3, y,
	      z) + temp387 * ti1 (x - 3,
	      y,
	      z)) * ti2 (x - 3, y,
	    z) - (4.16666666666667e-3 * (u (t, x - 3, y,
		z - 2) - u (t,
		x - 3, y,
		z + 2)) + 3.33333333333333e-2 * (-u (t,
		x - 3,
		y,
		z - 1) + u (t,
		x - 3,
		y,
		z + 1))) * ti0 (x - 3, y,
	    z)) * ti1 (x - 3,
	  y,
	  z) * ti2 (x - 3, y,
	  z) + 2.08333333333333e-3 * ((temp388 * ti1 (x, y - 3,
	      z) + temp390 * ti3 (x,
	      y - 3,
	      z)) * ti2 (x, y - 3,
	    z) - (-4.16666666666667e-2 * u (t, x, y - 3,
	      z) - 1.25e-2 * u (t, x,
	      y - 3,
	      z - 1) + 7.5e-2 * u (t, x,
	      y - 3,
	      z + 1) - 2.5e-2 * u (t, x,
	      y - 3,
	      z + 2) + 4.16666666666667e-3 * u (t, x, y - 3,
	      z + 3)) * ti0 (x,
	    y - 3,
	    z)) * ti2 (x, y - 3,
	  z) * ti3 (x,
	  y - 3,
	  z) + 3.75e-2 * ((temp399 * ti1 (x, y - 1,
	      z) + temp401 * ti3 (x,
	      y - 1,
	      z)) * ti2 (x, y - 1,
	    z) - (-4.16666666666667e-2 * u (t, x, y - 1,
	      z) - 1.25e-2 * u (t, x,
	      y - 1,
	      z - 1) + 7.5e-2 * u (t, x,
	      y - 1,
	      z + 1) - 2.5e-2 * u (t, x,
	      y - 1,
	      z + 2) + 4.16666666666667e-3 * u (t, x, y - 1,
	      z + 3)) * ti0 (x,
	    y - 1,
	    z)) * ti2 (x, y - 1,
	  z) * ti3 (x,
	  y - 1,
	  z) + 3.75e-2 * ((temp407 * ti3 (x - 1, y,
	      z) + temp408 * ti1 (x - 1,
	      y,
	      z)) * ti2 (x - 1, y,
	    z) - (4.16666666666667e-3 * (u (t, x - 1, y,
		z - 2) - u (t,
		x - 1,
		y,
		z + 2)) + 3.33333333333333e-2 * (-u (t,
		x - 1, y,
		z - 1) + u (t,
		x - 1,
		y,
		z + 1))) * ti0 (x - 1, y,
	    z)) * ti1 (x - 1,
	  y,
	  z) * ti2 (x - 1, y,
	  z) +
	2.08333333333333e-3 *
	(((4.16666666666667e-3 * (u (t, x, y - 2, z - 2) - u (t, x, y + 2,
		  z - 2)) + 3.33333333333333e-2 * (-u (t,
		  x,
		  y - 1,
		  z - 2) + u (t, x,
		  y + 1,
		  z - 2))) * ti3 (x, y,
	      z - 2) + (-4.16666666666667e-2 * u (t,
		x,
		y,
		z - 2) - 1.25e-2 * u (t,
		x - 1, y,
		z - 2) + 7.5e-2 * u (t,
		x + 1,
		y,
		z - 2) - 2.5e-2 * u (t,
		x + 2,
		y,
		z - 2) + 4.16666666666667e-3 * u (t,
		x + 3,
		y,
		z - 2)) * ti1 (x, y,
	      z - 2)) * ti2 (x, y,
	    z - 2) - (4.16666666666667e-3 * (-u (t, x, y, z) + u (t, x, y,
		z - 4)) + 3.33333333333333e-2 * (-u (t, x, y,
		z - 3) + u (t, x,
		y,
		z - 1))) * ti0 (x,
	    y,
	    z - 2)) * ti0 (x, y,
	  z - 2) +
	1.66666666666667e-2 *
	(((4.16666666666667e-3 * (u (t, x, y - 2, z + 1) - u (t, x, y + 2,
		  z + 1)) + 3.33333333333333e-2 * (-u (t,
		  x,
		  y - 1,
		  z + 1) + u (t, x,
		  y + 1,
		  z + 1))) * ti3 (x, y,
	      z + 1) + (-4.16666666666667e-2 * u (t,
		x,
		y,
		z + 1) - 1.25e-2 * u (t,
		x - 1, y,
		z + 1) + 7.5e-2 * u (t,
		x + 1,
		y,
		z + 1) - 2.5e-2 * u (t,
		x + 2,
		y,
		z + 1) + 4.16666666666667e-3 * u (t,
		x + 3,
		y,
		z + 1)) * ti1 (x, y,
	      z + 1)) * ti2 (x, y,
	    z + 1) - (3.33333333333333e-2 * (-u (t, x, y, z) + u (t, x, y,
		z + 2)) +
	    4.16666666666667e-3 * (u (t, x, y, z - 1) - u (t, x, y,
		z + 3))) * ti0 (x,
	    y,
	    z + 1)) * ti0 (x, y,
	  z + 1) +
	1.25e-2 *
	(((4.16666666666667e-3 * (u (t, x - 2, y, z - 2) - u (t, x + 2, y,
		  z - 2)) + 3.33333333333333e-2 * (-u (t,
		  x - 1,
		  y,
		  z - 2) + u (t,
		  x + 1,
		  y,
		  z - 2))) * ti1 (x, y,
	      z - 2) + (-4.16666666666667e-2 * u (t,
		x,
		y,
		z - 2) - 1.25e-2 * u (t, x,
		y - 1,
		z - 2) + 7.5e-2 * u (t, x,
		y + 1,
		z - 2) - 2.5e-2 * u (t, x,
		y + 2,
		z - 2) + 4.16666666666667e-3 * u (t,
		x,
		y + 3,
		z - 2)) * ti3 (x, y,
	      z - 2)) * ti2 (x, y,
	    z - 2) - (-2.5e-2 * u (t, x, y,
	      z) - 1.25e-2 * u (t, x,
	      y,
	      z - 3) - 4.16666666666667e-2 * u (t, x, y,
	      z - 2) + 7.5e-2 * u (t, x,
	      y,
	      z - 1) + 4.16666666666667e-3 * u (t, x, y,
	      z + 1)) * ti0 (x,
	    y,
	    z - 2)) * ti0 (x, y,
	  z - 2) +
	6.25e-3 *
	(((4.16666666666667e-3 * (u (t, x - 2, y, z + 1) - u (t, x + 2, y,
		  z + 1)) + 3.33333333333333e-2 * (-u (t,
		  x - 1,
		  y,
		  z + 1) + u (t,
		  x + 1,
		  y,
		  z + 1))) * ti1 (x, y,
	      z + 1) + (-4.16666666666667e-2 * u (t,
		x,
		y,
		z + 1) - 1.25e-2 * u (t, x,
		y - 1,
		z + 1) + 7.5e-2 * u (t, x,
		y + 1,
		z + 1) - 2.5e-2 * u (t, x,
		y + 2,
		z + 1) + 4.16666666666667e-3 * u (t,
		x,
		y + 3,
		z + 1)) * ti3 (x, y,
	      z + 1)) * ti2 (x, y,
	    z + 1) - (-1.25e-2 * u (t, x, y,
	      z) - 4.16666666666667e-2 * u (t, x, y,
	      z + 1) + 7.5e-2 * u (t, x,
	      y,
	      z + 2) - 2.5e-2 * u (t,
	      x,
	      y,
	      z + 3) + 4.16666666666667e-3 * u (t, x, y,
	      z + 4)) * ti0 (x,
	    y,
	    z + 1)) * ti0 (x, y, z + 1));
      auto temp290 =
	(((4.16666666666667e-3 * (-v (t, x, y, z) + v (t, x - 4, y,
		z)) + 3.33333333333333e-2 * (-v (t, x - 3, y, z) + v (t,
		x - 1, y, z))) * ti1 (x - 2, y,
	    z) + (-4.16666666666667e-2 * v (t, x - 2, y, z) - 1.25e-2 * v (t,
	      x - 2, y - 1, z) + 7.5e-2 * v (t, x - 2, y + 1,
	      z) - 2.5e-2 * v (t,
	      x - 2,
	      y + 2,
	      z) + 4.16666666666667e-3 * v (t, x - 2, y + 3, z)) * ti3 (x - 2,
	    y,
	    z)) * ti0 (x - 2,
	  y,
	  z) + (-4.16666666666667e-2 * v (t, x - 2, y,
	    z) - 1.25e-2 * v (t,
	    x - 2,
	    y,
	    z - 1) + 7.5e-2 * v (t, x - 2, y, z + 1) - 2.5e-2 * v (t,
	    x - 2,
	    y,
	    z + 2) + 4.16666666666667e-3 * v (t, x - 2, y,
	    z + 3)) * ti2 (x - 2,
	  y,
	  z)) * ti0 (x - 2,
	y,
	z) * ti1 (x - 2, y, z);
      auto temp275 =
	(((3.33333333333333e-2 * (v (t, x, y, z) - v (t, x, y - 2,
		z)) + 4.16666666666667e-3 * (v (t, x, y - 3, z) - v (t, x,
		y + 1, z))) * ti3 (x, y - 1,
	    z) + (-4.16666666666667e-2 * v (t, x, y - 1, z) - 1.25e-2 * v (t,
	      x - 1, y - 1, z) + 7.5e-2 * v (t, x + 1, y - 1,
	      z) - 2.5e-2 * v (t,
	      x + 2,
	      y - 1,
	      z) + 4.16666666666667e-3 * v (t, x + 3, y - 1, z)) * ti1 (x,
	    y - 1,
	    z)) * ti0 (x,
	  y - 1,
	  z)
	+ (4.16666666666667e-3 * (v (t, x, y - 1, z - 2) - v (t, x, y - 1,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x, y - 1, z - 1) + v (t,
	      x, y - 1, z + 1))) * ti2 (x, y - 1,
	  z)) * ti0 (x,
	y - 1,
	z) * ti3 (x, y - 1, z);
      auto temp237 =
	(((3.33333333333333e-2 * (-v (t, x, y, z) + v (t, x, y + 2,
		z)) + 4.16666666666667e-3 * (v (t, x, y - 1, z) - v (t, x,
		y + 3, z))) * ti3 (x, y + 1,
	    z) + (-4.16666666666667e-2 * v (t, x, y + 1, z) - 1.25e-2 * v (t,
	      x - 1, y + 1, z) + 7.5e-2 * v (t, x + 1, y + 1,
	      z) - 2.5e-2 * v (t,
	      x + 2,
	      y + 1,
	      z) + 4.16666666666667e-3 * v (t, x + 3, y + 1, z)) * ti1 (x,
	    y + 1,
	    z)) * ti0 (x,
	  y + 1,
	  z)
	+ (4.16666666666667e-3 * (v (t, x, y + 1, z - 2) - v (t, x, y + 1,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x, y + 1, z - 1) + v (t,
	      x, y + 1, z + 1))) * ti2 (x, y + 1,
	  z)) * ti0 (x,
	y + 1,
	z) * ti3 (x, y + 1, z);
      auto temp262 =
	(((4.16666666666667e-3 * (v (t, x, y, z) - v (t, x, y + 4,
		z)) + 3.33333333333333e-2 * (-v (t, x, y + 1, z) + v (t, x,
		y + 3, z))) * ti3 (x, y + 2,
	    z) + (-4.16666666666667e-2 * v (t, x, y + 2, z) - 1.25e-2 * v (t,
	      x - 1, y + 2, z) + 7.5e-2 * v (t, x + 1, y + 2,
	      z) - 2.5e-2 * v (t,
	      x + 2,
	      y + 2,
	      z) + 4.16666666666667e-3 * v (t, x + 3, y + 2, z)) * ti1 (x,
	    y + 2,
	    z)) * ti0 (x,
	  y + 2,
	  z)
	+ (4.16666666666667e-3 * (v (t, x, y + 2, z - 2) - v (t, x, y + 2,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x, y + 2, z - 1) + v (t,
	      x, y + 2, z + 1))) * ti2 (x, y + 2,
	  z)) * ti0 (x,
	y + 2,
	z) * ti3 (x, y + 2, z);
      auto temp68 =
	((4.16666666666667e-3 * (v (t, x - 2, y, z) - v (t, x + 2, y,
	      z)) + 3.33333333333333e-2 * (-v (t, x - 1, y, z) + v (t, x + 1,
	      y, z))) * ti1 (x, y,
	  z) + (-4.16666666666667e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x,
	    y - 1, z) + 7.5e-2 * v (t, x, y + 1,
	    z) - 2.5e-2 * v (t, x,
	    y + 2,
	    z) + 4.16666666666667e-3 * v (t, x, y + 3, z)) * ti3 (x, y,
	  z)) * ti0 (x,
	y,
	z)
	+ (-4.16666666666667e-2 * v (t, x, y, z) - 1.25e-2 * v (t, x, y,
	  z - 1) + 7.5e-2 * v (t, x, y,
	  z + 1) - 2.5e-2 * v (t,
	  x,
	  y,
	  z + 2) + 4.16666666666667e-3 * v (t, x, y, z + 3)) * ti2 (x, y, z);
      auto temp6 =
	1.0 / (8.85879567828298e-1 * damp (x, y, z) + 2.0 * m (x, y, z));
      auto temp225 =
	(((4.16666666666667e-3 * (v (t, x + 1, y - 2, z) - v (t, x + 1, y + 2,
		z)) + 3.33333333333333e-2 * (-v (t, x + 1, y - 1, z) + v (t,
		x + 1, y + 1, z))) * ti3 (x + 1, y,
	    z) + (-1.25e-2 * v (t, x, y, z) - 4.16666666666667e-2 * v (t,
	      x + 1, y, z) + 7.5e-2 * v (t, x + 2, y,
	      z) - 2.5e-2 * v (t, x + 3, y, z) + 4.16666666666667e-3 * v (t,
	      x + 4, y,
	      z)) * ti1 (x + 1,
	    y,
	    z)) * ti0 (x + 1, y,
	  z) +
	(4.16666666666667e-3 * (v (t, x + 1, y, z - 2) - v (t, x + 1, y,
	      z + 2)) + 3.33333333333333e-2 * (-v (t, x + 1, y, z - 1) + v (t,
	      x + 1, y, z + 1))) * ti2 (x + 1, y,
	  z)) * ti0 (x + 1,
	y,
	z) * ti1 (x + 1, y, z);

      // Next time-step values.
      u (t + 1, x, y,
	z) EQUALS temp6 *(temp10 * u (t - 1, x, y,
	  z) +
	1.5695652173913 * (temp487 * epsilon (x, y, z) +
	  (2.08333333333333e-2 *
	    (temp56 +
	      temp68 * (ti0 (x, y, z) *
		ti3 (x, y,
		  z) + ti2 (x, y,
		  z))) +
	    1.25e-2 * (temp185 + temp284 +
	      temp308) -
	    3.75e-2 * (temp204 + temp286 +
	      temp309) +
	    6.25e-3 * (temp225 + temp288 +
	      temp310) +
	    1.66666666666667e-2 *
	    (-temp154 + temp237 - temp275 +
	      temp289 - temp299 + temp92) + 2.08333333333333e-3 * (temp116 -
	      temp133 - temp165 + temp252 - temp262 - temp283 + temp290 -
	      temp298 - temp307)) * delta (x, y, z)) + 4.0 * m (x, y,
	  z) * u (t, x, y, z));
      v (t + 1, x, y, z) EQUALS temp6 *(temp10 * v (t - 1, x, y,
	  z) + 1.5695652173913 * temp487 * delta (x, y,
	  z) + 3.26992753623188e-2 * (temp56 + temp68 * (ti0 (x, y,
	      z) * ti3 (x, y, z) + ti2 (x, y,
	      z))) + 1.96195652173913e-2 * (temp185 + temp284 + temp308) -
	5.88586956521739e-2 * (temp204 + temp286 + temp309) +
	9.80978260869565e-3 * (temp225 + temp288 + temp310) +
	2.61594202898551e-2 * (-temp154 + temp237 - temp275 + temp289 -
	  temp299 + temp92) + 3.26992753623188e-3 * (temp116 - temp133 -
	  temp165 + temp252 - temp262 - temp283 + temp290 - temp298 -
	  temp307) + 4.0 * m (x, y, z) * v (t, x, y, z));

    }

    // Required stencil-definition method.
    virtual void define ()
    {
      switch (get_radius ())
	{
	case 2:
	  define_so4 ();
	  break;
	case 4:
	  define_so8 ();
	  break;
	default:
	  {
	    yask_exception
	      e
	      ("Error: only radius values of 2 and 4 are currently supported for the TTI stencil example");
	    throw e;
	  }
	}
    }
  };

  // Create an object of type 'TTIStencil',
  // making it available in the YASK compiler utility via the
  // '-stencil' commmand-line option or the 'stencil=' build option.
  static TTIStencil TTIStencil_instance;

}				// namespace.
